/* AI-generated by Codex/Claude. */

#include "tutorial/lesson01/event_timeline.hh"

#include <sstream>

#include "sim/cur_tick.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson01
{

EventTimeline::EventTimeline(EventQueue *event_queue)
    : EventManager(event_queue),
      bootstrapEvent(
          [this]() { onBootstrap(); },
          "tutorial.lesson01.bootstrap"),
      highPriorityEvent(
          [this]() { onHighPriorityPhase(); },
          "tutorial.lesson01.high_priority",
          false,
          EventBase::Delayed_Writeback_Pri),
      defaultPriorityEvent(
          [this]() { onDefaultPriorityPhase(); },
          "tutorial.lesson01.default_priority",
          false,
          EventBase::Default_Pri),
      lowPriorityPulseEvent(
          [this]() { onLowPriorityPulse(); },
          "tutorial.lesson01.low_priority_pulse",
          false,
          EventBase::Progress_Event_Pri)
{
}

void
EventTimeline::prime()
{
    schedule(bootstrapEvent, 3);
}

void
EventTimeline::runToCompletion()
{
    while (!eventQueue()->empty()) {
        eventQueue()->serviceOne();
    }
}

void
EventTimeline::appendTrace(const std::string &label)
{
    std::ostringstream entry;
    entry << "tick=" << curTick() << " label=" << label;
    eventTrace.push_back(entry.str());
    callbackCount++;
}

void
EventTimeline::onBootstrap()
{
    appendTrace("bootstrap");

    // These three callbacks all run at tick 7. Their priorities determine
    // execution order: high, then default, then low.
    schedule(highPriorityEvent, 7);
    schedule(defaultPriorityEvent, 7);
    schedule(lowPriorityPulseEvent, 7);
}

void
EventTimeline::onHighPriorityPhase()
{
    appendTrace("high-priority-phase");
}

void
EventTimeline::onDefaultPriorityPhase()
{
    appendTrace("default-priority-phase");
}

void
EventTimeline::onLowPriorityPulse()
{
    appendTrace("low-priority-pulse");
    pulseCount++;

    // Keep one event chain going to show repeated self-scheduling.
    if (pulseCount < 3) {
        schedule(lowPriorityPulseEvent, curTick() + 2);
    }
}

} // namespace lesson01

} // namespace tutorial

} // namespace gem5
