/* AI-generated by Codex/Claude. */

#ifndef __TUTORIAL_LESSON01_EVENT_TIMELINE_HH__
#define __TUTORIAL_LESSON01_EVENT_TIMELINE_HH__

#include <cstdint>
#include <string>
#include <vector>

#include "sim/eventq.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson01
{

/**
 * A minimal event-driven timeline used by Lesson 1.
 *
 * The class uses gem5's EventManager API to schedule named callbacks and keeps
 * a textual trace of what happened at each tick. It intentionally demonstrates
 * two fundamental behaviors:
 *
 * 1) Event ordering by time.
 * 2) Event ordering by priority when time is identical.
 */
class EventTimeline : public EventManager
{
  public:
    explicit EventTimeline(EventQueue *event_queue);

    /** Schedule the initial "bootstrap" event that seeds the timeline. */
    void prime();

    /** Service events until this event queue becomes empty. */
    void runToCompletion();

    const std::vector<std::string> &trace() const { return eventTrace; }
    std::uint64_t callbacksExecuted() const { return callbackCount; }

  private:
    /** Store a normalized trace line, e.g., "tick=7 label=phase-A". */
    void appendTrace(const std::string &label);

    void onBootstrap();
    void onHighPriorityPhase();
    void onDefaultPriorityPhase();
    void onLowPriorityPulse();

    std::vector<std::string> eventTrace;
    std::uint64_t callbackCount = 0;
    int pulseCount = 0;

    EventFunctionWrapper bootstrapEvent;
    EventFunctionWrapper highPriorityEvent;
    EventFunctionWrapper defaultPriorityEvent;
    EventFunctionWrapper lowPriorityPulseEvent;
};

} // namespace lesson01

} // namespace tutorial

} // namespace gem5

#endif // __TUTORIAL_LESSON01_EVENT_TIMELINE_HH__
