/* AI-generated by Codex/Claude. */

#include <gtest/gtest.h>

#include <sstream>
#include <string>
#include <vector>

#include "mem/packet.hh"
#include "mem/port.hh"
#include "mem/request.hh"
#include "params/TutorialMemoryBridge.hh"
#include "sim/eventq.hh"
#include "tutorial/lesson03/memory_ports.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson03
{

/*
 * ---------------------------------------------------------------------------
 * Test harness: a mock requester and a mock responder that sit on either
 * side of the TutorialMemoryBridge.
 *
 *   MockRequester                                       MockResponder
 *  (RequestPort)  <---->  [ TutorialMemoryBridge ]  <---->  (ResponsePort)
 *   sends reqs            upstream       downstream         answers reqs
 *   receives resps                                          with responses
 * ---------------------------------------------------------------------------
 */

/**
 * A mock request port that drives read/write requests into the bridge's
 * upstream ResponsePort. It records responses for test verification.
 */
class MockRequesterPort : public RequestPort
{
  public:
    MockRequesterPort(const std::string &name)
        : RequestPort(name),
          responseCount(0),
          blockedPacket(nullptr)
    {}

    /** Build and send a read request for the given address. */
    void sendReadRequest(Addr addr, unsigned size)
    {
        auto req = std::make_shared<Request>(
            addr, size, Request::Flags(), Request::invldRequestorId);
        auto pkt = new Packet(req, MemCmd::ReadReq);
        pkt->allocate();
        sendPacket(pkt);
    }

    /** Build and send a write request for the given address. */
    void sendWriteRequest(Addr addr, unsigned size)
    {
        auto req = std::make_shared<Request>(
            addr, size, Request::Flags(), Request::invldRequestorId);
        auto pkt = new Packet(req, MemCmd::WriteReq);
        pkt->allocate();
        sendPacket(pkt);
    }

    unsigned responseCount;
    std::vector<std::string> responseLog;
    bool wasBlocked = false;

  protected:
    bool
    recvTimingResp(PacketPtr pkt) override
    {
        responseCount++;
        std::ostringstream entry;
        entry << "resp addr=0x" << std::hex << pkt->getAddr()
              << " cmd=" << pkt->cmd.toString();
        responseLog.push_back(entry.str());
        delete pkt;
        return true;
    }

    void
    recvReqRetry() override
    {
        PacketPtr pkt = blockedPacket;
        blockedPacket = nullptr;
        sendPacket(pkt);
    }

  private:
    void
    sendPacket(PacketPtr pkt)
    {
        if (!sendTimingReq(pkt)) {
            blockedPacket = pkt;
            wasBlocked = true;
        }
    }

    PacketPtr blockedPacket;
};

/**
 * A mock response port that acts as a trivial memory: it immediately
 * converts any incoming timing request into a response and sends it
 * back. This lets us test the bridge in isolation.
 */
class MockResponderPort : public ResponsePort
{
  public:
    MockResponderPort(const std::string &name, AddrRange range)
        : ResponsePort(name),
          requestCount(0),
          addrRange(range)
    {}

    unsigned requestCount;

  protected:
    AddrRangeList
    getAddrRanges() const override
    {
        return {addrRange};
    }

    Tick
    recvAtomic(PacketPtr pkt) override
    {
        pkt->makeAtomicResponse();
        return 1;
    }

    void
    recvFunctional(PacketPtr pkt) override
    {
        pkt->makeResponse();
    }

    bool
    recvTimingReq(PacketPtr pkt) override
    {
        requestCount++;
        pkt->makeResponse();
        sendTimingResp(pkt);
        return true;
    }

    void
    recvRespRetry() override
    {
    }

  private:
    AddrRange addrRange;
};


// ---------------------------------------------------------------------------
// Test fixture
// ---------------------------------------------------------------------------

class MemoryPortsTest : public ::testing::Test
{
  protected:
    EventQueue *queue = nullptr;
    EventQueue *savedQueue = nullptr;

    void
    SetUp() override
    {
        queue = getEventQueue(0);
        savedQueue = curEventQueue();
        curEventQueue(queue);

        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
    }

    void
    TearDown() override
    {
        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
        curEventQueue(savedQueue);
    }
};


// ---------------------------------------------------------------------------
// Test cases
// ---------------------------------------------------------------------------

TEST_F(MemoryPortsTest, ForwardsReadRequestAndResponse)
{
    // Create bridge.
    TutorialMemoryBridgeParams params;
    params.name = "test.bridge";
    params.eventq_index = 0;
    params.response_latency = 0;

    TutorialMemoryBridge bridge(params);

    // Create mock endpoints.
    MockRequesterPort requester("test.requester");
    MockResponderPort responder("test.responder",
                                AddrRange(0x0, 0x1000));

    // Bind: requester <-> bridge.upstream,
    //        bridge.downstream <-> responder.
    Port &upPort = bridge.getPort("upstream");
    Port &downPort = bridge.getPort("downstream");

    requester.bind(upPort);
    downPort.bind(responder);

    bridge.init();

    // Send a read request.
    requester.sendReadRequest(0x100, 4);

    EXPECT_EQ(responder.requestCount, 1u);
    EXPECT_EQ(requester.responseCount, 1u);
    EXPECT_EQ(bridge.requestsForwarded(), 1u);
    EXPECT_EQ(bridge.responsesDelivered(), 1u);

    ASSERT_EQ(requester.responseLog.size(), 1u);
    EXPECT_EQ(requester.responseLog[0], "resp addr=0x100 cmd=ReadResp");
}

TEST_F(MemoryPortsTest, ForwardsWriteRequestAndResponse)
{
    TutorialMemoryBridgeParams params;
    params.name = "test.bridge";
    params.eventq_index = 0;
    params.response_latency = 0;

    TutorialMemoryBridge bridge(params);

    MockRequesterPort requester("test.requester");
    MockResponderPort responder("test.responder",
                                AddrRange(0x0, 0x1000));

    Port &upPort = bridge.getPort("upstream");
    Port &downPort = bridge.getPort("downstream");

    requester.bind(upPort);
    downPort.bind(responder);

    bridge.init();

    requester.sendWriteRequest(0x200, 8);

    EXPECT_EQ(responder.requestCount, 1u);
    EXPECT_EQ(requester.responseCount, 1u);
    EXPECT_EQ(bridge.requestsForwarded(), 1u);

    ASSERT_EQ(requester.responseLog.size(), 1u);
    EXPECT_EQ(requester.responseLog[0], "resp addr=0x200 cmd=WriteResp");
}

TEST_F(MemoryPortsTest, BackpressureBlocksSecondRequest)
{
    // Use a nonzero response latency so that the first request stays
    // in flight when the second one arrives.
    TutorialMemoryBridgeParams params;
    params.name = "test.bridge";
    params.eventq_index = 0;
    params.response_latency = 5;

    TutorialMemoryBridge bridge(params);

    MockRequesterPort requester("test.requester");
    MockResponderPort responder("test.responder",
                                AddrRange(0x0, 0x1000));

    Port &upPort = bridge.getPort("upstream");
    Port &downPort = bridge.getPort("downstream");

    requester.bind(upPort);
    downPort.bind(responder);

    bridge.init();

    // First request succeeds.
    requester.sendReadRequest(0x100, 4);
    EXPECT_EQ(bridge.requestsForwarded(), 1u);

    // Response is delayed, so bridge is still blocked.
    EXPECT_EQ(requester.responseCount, 0u);

    // Second request should be rejected (backpressure).
    requester.sendReadRequest(0x200, 4);
    EXPECT_TRUE(requester.wasBlocked);
    EXPECT_EQ(bridge.requestsForwarded(), 1u);

    // Drain all pending events. The first delayed response triggers a retry,
    // which resubmits the second request and schedules its delayed response.
    // runToCompletion() therefore delivers both responses.
    bridge.runToCompletion();

    // The retry should have allowed the second request through, and both
    // responses should have been delivered by the queue drain.
    EXPECT_EQ(bridge.requestsForwarded(), 2u);
    EXPECT_EQ(responder.requestCount, 2u);
    EXPECT_EQ(requester.responseCount, 2u);
    EXPECT_EQ(bridge.responsesDelivered(), 2u);
}

TEST_F(MemoryPortsTest, ResponseLatencyAddsDelay)
{
    TutorialMemoryBridgeParams params;
    params.name = "test.bridge";
    params.eventq_index = 0;
    params.response_latency = 10;

    TutorialMemoryBridge bridge(params);

    MockRequesterPort requester("test.requester");
    MockResponderPort responder("test.responder",
                                AddrRange(0x0, 0x1000));

    Port &upPort = bridge.getPort("upstream");
    Port &downPort = bridge.getPort("downstream");

    requester.bind(upPort);
    downPort.bind(responder);

    bridge.init();

    // Send at tick 0.
    requester.sendReadRequest(0x100, 4);

    // Not yet delivered.
    EXPECT_EQ(requester.responseCount, 0u);
    EXPECT_EQ(queue->getCurTick(), 0u);

    // Run to completion: response arrives at tick 10.
    bridge.runToCompletion();

    EXPECT_EQ(queue->getCurTick(), 10u);
    EXPECT_EQ(requester.responseCount, 1u);
    EXPECT_EQ(bridge.responsesDelivered(), 1u);
}

TEST_F(MemoryPortsTest, EventLogTracksRequestFlow)
{
    TutorialMemoryBridgeParams params;
    params.name = "test.bridge";
    params.eventq_index = 0;
    params.response_latency = 0;

    TutorialMemoryBridge bridge(params);

    MockRequesterPort requester("test.requester");
    MockResponderPort responder("test.responder",
                                AddrRange(0x0, 0x1000));

    Port &upPort = bridge.getPort("upstream");
    Port &downPort = bridge.getPort("downstream");

    requester.bind(upPort);
    downPort.bind(responder);

    bridge.init();

    requester.sendReadRequest(0x100, 4);

    const auto &log = bridge.eventLog();

    // Should contain: construct, init, forward-req, recv-resp,
    // deliver-resp.
    ASSERT_GE(log.size(), 5u);
    EXPECT_EQ(log[0], "tick=0 construct");
    EXPECT_EQ(log[1], "tick=0 init");
    EXPECT_NE(log[2].find("forward-req"), std::string::npos);
    EXPECT_NE(log[3].find("recv-resp"), std::string::npos);
    EXPECT_NE(log[4].find("deliver-resp"), std::string::npos);
}

} // namespace lesson03

} // namespace tutorial

} // namespace gem5
