/* AI-generated by Codex/Claude. */

#ifndef __TUTORIAL_LESSON03_MEMORY_PORTS_HH__
#define __TUTORIAL_LESSON03_MEMORY_PORTS_HH__

#include <cstdint>
#include <string>
#include <vector>

#include "mem/packet.hh"
#include "mem/port.hh"
#include "params/TutorialMemoryBridge.hh"
#include "sim/sim_object.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson03
{

/**
 * A minimal pass-through memory bridge used by Lesson 3 to demonstrate
 * ports, packets, and the timing request/response flow.
 *
 * The bridge sits between a request source and a memory responder. It
 * accepts timing requests on its ResponsePort (upstream side), forwards
 * them to its RequestPort (downstream side), receives timing responses,
 * and forwards them back upstream.
 *
 * The bridge is fully blocking: it accepts at most one outstanding
 * request at a time. If a second request arrives while one is in
 * flight, the bridge returns false (backpressure) and later sends a
 * retry notification.
 *
 * A configurable response latency adds a delay between receiving the
 * downstream response and forwarding it upstream, demonstrating how
 * event scheduling integrates with the port protocol.
 */
class TutorialMemoryBridge : public SimObject
{
  public:
    PARAMS(TutorialMemoryBridge);
    explicit TutorialMemoryBridge(const Params &p);

    Port &getPort(const std::string &if_name,
                  PortID idx = InvalidPortID) override;

    void init() override;

    /** Test helper: run events until the queue drains. */
    void runToCompletion();

    const std::vector<std::string> &eventLog() const
    {
        return traceLog;
    }

    std::uint64_t requestsForwarded() const { return forwardedCount; }
    std::uint64_t responsesDelivered() const { return deliveredCount; }

  private:
    /** The port that faces upstream (toward the requester). */
    class UpstreamPort : public ResponsePort
    {
      public:
        UpstreamPort(const std::string &name,
                     TutorialMemoryBridge &owner);

        void sendPacket(PacketPtr pkt);
        void trySendRetry();
        void notifyRangeChange();

        AddrRangeList getAddrRanges() const override;

      protected:
        Tick recvAtomic(PacketPtr pkt) override;
        void recvFunctional(PacketPtr pkt) override;
        bool recvTimingReq(PacketPtr pkt) override;
        void recvRespRetry() override;

      private:
        TutorialMemoryBridge &bridge;
        bool needRetry;
        PacketPtr blockedPacket;
    };

    /** The port that faces downstream (toward memory). */
    class DownstreamPort : public RequestPort
    {
      public:
        DownstreamPort(const std::string &name,
                       TutorialMemoryBridge &owner);

        void sendPacket(PacketPtr pkt);

      protected:
        bool recvTimingResp(PacketPtr pkt) override;
        void recvReqRetry() override;
        void recvRangeChange() override;

      private:
        TutorialMemoryBridge &bridge;
        PacketPtr blockedPacket;
    };

    bool handleRequest(PacketPtr pkt);
    bool handleResponse(PacketPtr pkt);
    void processResponseEvent();
    AddrRangeList getAddrRanges() const;
    void sendRangeChange();

    void appendLog(const std::string &entry);

    UpstreamPort upstreamPort;
    DownstreamPort downstreamPort;

    /** True while a request is in flight. */
    bool blocked;

    /** Configurable extra latency added to responses. */
    const Tick responseLatency;

    /** Packet waiting for the response-latency delay. */
    PacketPtr pendingResponse;

    /** Event for delivering delayed response. */
    EventFunctionWrapper responseEvent;

    std::vector<std::string> traceLog;
    std::uint64_t forwardedCount = 0;
    std::uint64_t deliveredCount = 0;
};

} // namespace lesson03

} // namespace tutorial

} // namespace gem5

#endif // __TUTORIAL_LESSON03_MEMORY_PORTS_HH__
