/* AI-generated by Codex/Claude. */

#include "tutorial/lesson03/memory_ports.hh"

#include <sstream>

#include "sim/cur_tick.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson03
{

// --- TutorialMemoryBridge ---------------------------------------------------

TutorialMemoryBridge::TutorialMemoryBridge(const Params &p)
    : SimObject(p),
      upstreamPort(p.name + ".upstream", *this),
      downstreamPort(p.name + ".downstream", *this),
      blocked(false),
      responseLatency(p.response_latency),
      pendingResponse(nullptr),
      responseEvent(
          [this]() { processResponseEvent(); },
          p.name + ".response_event")
{
    appendLog("construct");
}

Port &
TutorialMemoryBridge::getPort(
    const std::string &if_name, PortID idx)
{
    if (if_name == "upstream") {
        return upstreamPort;
    } else if (if_name == "downstream") {
        return downstreamPort;
    } else {
        return SimObject::getPort(if_name, idx);
    }
}

void
TutorialMemoryBridge::init()
{
    appendLog("init");

    // Propagate address ranges from downstream to upstream once both
    // sides are connected.
    upstreamPort.notifyRangeChange();
}

void
TutorialMemoryBridge::runToCompletion()
{
    while (!eventQueue()->empty()) {
        eventQueue()->serviceOne();
    }
}

bool
TutorialMemoryBridge::handleRequest(PacketPtr pkt)
{
    if (blocked) {
        appendLog("backpressure");
        return false;
    }

    blocked = true;
    forwardedCount++;

    std::ostringstream entry;
    entry << "forward-req addr=0x" << std::hex << pkt->getAddr()
          << " cmd=" << pkt->cmd.toString();
    appendLog(entry.str());

    downstreamPort.sendPacket(pkt);
    return true;
}

bool
TutorialMemoryBridge::handleResponse(PacketPtr pkt)
{
    std::ostringstream entry;
    entry << "recv-resp addr=0x" << std::hex << pkt->getAddr()
          << " cmd=" << pkt->cmd.toString();
    appendLog(entry.str());

    if (responseLatency > 0) {
        pendingResponse = pkt;
        schedule(responseEvent, curTick() + responseLatency);
        return true;
    }

    // Zero latency: deliver immediately.
    blocked = false;
    deliveredCount++;
    appendLog("deliver-resp");
    upstreamPort.sendPacket(pkt);
    upstreamPort.trySendRetry();
    return true;
}

void
TutorialMemoryBridge::processResponseEvent()
{
    PacketPtr pkt = pendingResponse;
    pendingResponse = nullptr;

    blocked = false;
    deliveredCount++;
    appendLog("deliver-resp");
    upstreamPort.sendPacket(pkt);
    upstreamPort.trySendRetry();
}

AddrRangeList
TutorialMemoryBridge::getAddrRanges() const
{
    return downstreamPort.getAddrRanges();
}

void
TutorialMemoryBridge::sendRangeChange()
{
    upstreamPort.notifyRangeChange();
}

void
TutorialMemoryBridge::appendLog(const std::string &entry)
{
    std::ostringstream line;
    line << "tick=" << curTick() << " " << entry;
    traceLog.push_back(line.str());
}

// --- UpstreamPort -----------------------------------------------------------

TutorialMemoryBridge::UpstreamPort::UpstreamPort(
    const std::string &name,
    TutorialMemoryBridge &owner)
    : ResponsePort(name),
      bridge(owner),
      needRetry(false),
      blockedPacket(nullptr)
{
}

void
TutorialMemoryBridge::UpstreamPort::sendPacket(PacketPtr pkt)
{
    if (!sendTimingResp(pkt)) {
        blockedPacket = pkt;
    }
}

void
TutorialMemoryBridge::UpstreamPort::trySendRetry()
{
    if (needRetry && blockedPacket == nullptr) {
        needRetry = false;
        sendRetryReq();
    }
}

void
TutorialMemoryBridge::UpstreamPort::notifyRangeChange()
{
    sendRangeChange();
}

AddrRangeList
TutorialMemoryBridge::UpstreamPort::getAddrRanges() const
{
    return bridge.getAddrRanges();
}

Tick
TutorialMemoryBridge::UpstreamPort::recvAtomic(PacketPtr pkt)
{
    return bridge.downstreamPort.sendAtomic(pkt);
}

void
TutorialMemoryBridge::UpstreamPort::recvFunctional(PacketPtr pkt)
{
    bridge.downstreamPort.sendFunctional(pkt);
}

bool
TutorialMemoryBridge::UpstreamPort::recvTimingReq(PacketPtr pkt)
{
    if (!bridge.handleRequest(pkt)) {
        needRetry = true;
        return false;
    }
    return true;
}

void
TutorialMemoryBridge::UpstreamPort::recvRespRetry()
{
    PacketPtr pkt = blockedPacket;
    blockedPacket = nullptr;
    if (pkt != nullptr) {
        sendPacket(pkt);
    }
}

// --- DownstreamPort ---------------------------------------------------------

TutorialMemoryBridge::DownstreamPort::DownstreamPort(
    const std::string &name,
    TutorialMemoryBridge &owner)
    : RequestPort(name),
      bridge(owner),
      blockedPacket(nullptr)
{
}

void
TutorialMemoryBridge::DownstreamPort::sendPacket(PacketPtr pkt)
{
    if (!sendTimingReq(pkt)) {
        blockedPacket = pkt;
    }
}

bool
TutorialMemoryBridge::DownstreamPort::recvTimingResp(PacketPtr pkt)
{
    return bridge.handleResponse(pkt);
}

void
TutorialMemoryBridge::DownstreamPort::recvReqRetry()
{
    PacketPtr pkt = blockedPacket;
    blockedPacket = nullptr;
    if (pkt != nullptr) {
        sendPacket(pkt);
    }
}

void
TutorialMemoryBridge::DownstreamPort::recvRangeChange()
{
    bridge.sendRangeChange();
}

} // namespace lesson03

} // namespace tutorial

} // namespace gem5
