# AI-generated by Codex/Claude.

from m5.params import *
from m5.SimObject import SimObject


class TutorialMemoryBridge(SimObject):
    type = "TutorialMemoryBridge"
    cxx_header = "tutorial/lesson03/memory_ports.hh"
    cxx_class = "gem5::tutorial::lesson03::TutorialMemoryBridge"

    upstream = ResponsePort("Port facing the requester (CPU side)")
    downstream = RequestPort("Port facing memory (memory side)")

    response_latency = Param.Tick(
        0,
        "Extra ticks of delay before forwarding a response upstream",
    )
