# Copyright (c) 2026 ripopov
# SPDX-License-Identifier: BSD-3-Clause

Import('*')

SimObject('ChiTestbenchGem5.py', sim_objects=[
    'ChiSeqDriver',
    'ChiGem5Barrier',
    'ChiGem5EventBus',
])

Source('driver.cc')  # driver.cc also defines SeqThread::main()
Source('sync/barrier.cc')
Source('sync/latch.cc')
Source('sequences/registry.cc')
Source('sequences/idle.cc')
Source('sequences/smoke_read.cc')
Source('sequences/smoke_write.cc')
Source('sequences/smoke_opcode_mix.cc')
Source('sequences/ping_pong.cc')
Source('sequences/false_sharing.cc')
Source('sequences/memcpy.cc')
Source('sequences/memset.cc')
Source('sequences/opcode_walk.cc')
Source('sequences/read_ex_walk.cc')

DebugFlag('ChiTestbenchGem5')
