# Copyright (c) 2026 ripopov
# SPDX-License-Identifier: BSD-3-Clause

Import('*')

SimObject('ChiTestbenchGem5.py', sim_objects=[
    'ChiSeqDriver',
    'ChiGem5Barrier',
    'ChiGem5EventBus',
])

SimObject('ChiSequence.py', sim_objects=[
    'ChiSequence',
    'PingPongSequence',
    'MemsetSequence',
])

Source('driver.cc')  # driver.cc also defines SeqThread::main()
Source('sync/barrier.cc')
Source('sync/latch.cc')
Source('sequences/ping_pong.cc')
Source('sequences/memset.cc')

DebugFlag('ChiTestbenchGem5')
