/* AI-generated by Codex/Claude. */

#include "tutorial/lesson04/clock_domains.hh"

#include <sstream>

#include "sim/cur_tick.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson04
{

ClockedProbe::ClockedProbe(const std::string &label,
                           ClockDomain &clock_domain,
                           EventQueue *event_queue)
    : Clocked(clock_domain),
      EventManager(event_queue),
      probeLabel(label),
      pulseEvent([this]() { onPulse(); }, label + ".pulse")
{
    appendTrace("construct");
}

void
ClockedProbe::sample(const std::string &tag)
{
    appendTrace(tag);
}

void
ClockedProbe::schedulePulse(Cycles cycles_from_now)
{
    if (pulseEvent.scheduled()) {
        deschedule(pulseEvent);
    }

    schedule(pulseEvent, clockEdge(cycles_from_now));
}

void
ClockedProbe::runToCompletion()
{
    while (!eventQueue()->empty()) {
        eventQueue()->serviceOne();
    }
}

void
ClockedProbe::appendTrace(const std::string &tag)
{
    std::ostringstream line;
    line << "tick=" << curTick()
         << " label=" << probeLabel
         << " tag=" << tag
         << " period=" << clockPeriod()
         << " cycle=" << curCycle()
         << " edge=" << clockEdge()
         << " next=" << nextCycle();
    traceLog.push_back(line.str());
}

void
ClockedProbe::onPulse()
{
    pulseCount++;

    std::ostringstream tag;
    tag << "pulse-" << pulseCount;
    appendTrace(tag.str());
}

void
ClockedProbe::clockPeriodUpdated()
{
    clockUpdateCount++;

    std::ostringstream tag;
    tag << "clock-period-updated-" << clockUpdateCount;
    appendTrace(tag.str());
}

} // namespace lesson04

} // namespace tutorial

} // namespace gem5
