/* AI-generated by Codex/Claude. */

#ifndef __TUTORIAL_LESSON04_CLOCK_DOMAINS_HH__
#define __TUTORIAL_LESSON04_CLOCK_DOMAINS_HH__

#include <cstdint>
#include <string>
#include <vector>

#include "sim/clock_domain.hh"
#include "sim/clocked_object.hh"
#include "sim/eventq.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson04
{

/**
 * A small helper used by Lesson 4 to demonstrate clock-domain behavior.
 *
 * The probe is intentionally minimal: it inherits gem5's Clocked interface to
 * expose cycle/tick conversion helpers and inherits EventManager so it can
 * schedule callbacks on a queue.
 */
class ClockedProbe : public Clocked, public EventManager
{
  public:
    ClockedProbe(const std::string &label,
                 ClockDomain &clock_domain,
                 EventQueue *event_queue);

    /**
     * Capture the current clock state in a normalized, test-friendly line.
     */
    void sample(const std::string &tag);

    /**
     * Schedule one pulse event on this probe's future clock edge.
     */
    void schedulePulse(Cycles cycles_from_now);

    /**
     * Service the backing event queue until no events remain.
     */
    void runToCompletion();

    const std::vector<std::string> &trace() const { return traceLog; }
    std::uint64_t pulsesSeen() const { return pulseCount; }
    std::uint64_t clockUpdates() const { return clockUpdateCount; }

  private:
    void appendTrace(const std::string &tag);
    void onPulse();
    void clockPeriodUpdated() override;

    std::string probeLabel;
    std::vector<std::string> traceLog;
    std::uint64_t pulseCount = 0;
    std::uint64_t clockUpdateCount = 0;

    EventFunctionWrapper pulseEvent;
};

} // namespace lesson04

} // namespace tutorial

} // namespace gem5

#endif // __TUTORIAL_LESSON04_CLOCK_DOMAINS_HH__
