/* AI-generated by Codex/Claude. */

#include <gtest/gtest.h>

#include <string>

#include "params/DerivedClockDomain.hh"
#include "params/SrcClockDomain.hh"
#include "params/VoltageDomain.hh"
#include "sim/clock_domain.hh"
#include "sim/eventq.hh"
#include "sim/voltage_domain.hh"
#include "tutorial/lesson04/clock_domains.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson04
{

class ClockDomainsTest : public ::testing::Test
{
  protected:
    EventQueue *queue = nullptr;
    EventQueue *savedQueue = nullptr;

    void
    SetUp() override
    {
        queue = getEventQueue(0);
        savedQueue = curEventQueue();
        curEventQueue(queue);

        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
    }

    void
    TearDown() override
    {
        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
        curEventQueue(savedQueue);
    }
};

struct DomainBundle
{
    static VoltageDomainParams
    makeVoltageParams()
    {
        VoltageDomainParams params;
        params.name = "tutorial.lesson04.vdd";
        params.eventq_index = 0;
        params.voltage = {1.0, 0.9};
        return params;
    }

    static SrcClockDomainParams
    makeSourceParams(VoltageDomain *voltage_domain)
    {
        SrcClockDomainParams params;
        params.name = "tutorial.lesson04.src_clk";
        params.eventq_index = 0;
        // 0 = fastest point (smaller period, higher frequency).
        params.clock = {500, 1000};
        params.domain_id = 4;
        params.init_perf_level = 0;
        params.voltage_domain = voltage_domain;
        return params;
    }

    static DerivedClockDomainParams
    makeDerivedParams(ClockDomain *parent_domain)
    {
        DerivedClockDomainParams params;
        params.name = "tutorial.lesson04.mem_clk";
        params.eventq_index = 0;
        params.clk_divider = 2;
        params.clk_domain = parent_domain;
        return params;
    }

    VoltageDomainParams voltageParams;
    VoltageDomain voltageDomain;
    SrcClockDomainParams sourceParams;
    SrcClockDomain sourceDomain;
    DerivedClockDomainParams derivedParams;
    DerivedClockDomain derivedDomain;

    DomainBundle()
        : voltageParams(makeVoltageParams()),
          voltageDomain(voltageParams),
          sourceParams(makeSourceParams(&voltageDomain)),
          sourceDomain(sourceParams),
          derivedParams(makeDerivedParams(&sourceDomain)),
          derivedDomain(derivedParams)
    {
    }
};

TEST_F(ClockDomainsTest, ClockedHelpersConvertBetweenCyclesAndTicks)
{
    DomainBundle domains;
    ClockedProbe sourceProbe("source_probe", domains.sourceDomain, queue);
    ClockedProbe memoryProbe("memory_probe", domains.derivedDomain, queue);

    EXPECT_EQ(domains.sourceDomain.clockPeriod(), 500);
    EXPECT_EQ(domains.derivedDomain.clockPeriod(), 1000);
    EXPECT_DOUBLE_EQ(domains.voltageDomain.voltage(), 1.0);

    EXPECT_EQ(sourceProbe.clockEdge(), 0);
    EXPECT_EQ(sourceProbe.clockEdge(Cycles(2)), 1000);
    EXPECT_EQ(sourceProbe.cyclesToTicks(Cycles(3)), 1500);
    EXPECT_EQ(sourceProbe.ticksToCycles(501), Cycles(2));

    EXPECT_EQ(memoryProbe.clockEdge(), 0);
    EXPECT_EQ(memoryProbe.clockEdge(Cycles(2)), 2000);
    EXPECT_EQ(memoryProbe.cyclesToTicks(Cycles(3)), 3000);
    EXPECT_EQ(memoryProbe.ticksToCycles(1001), Cycles(2));

    queue->setCurTick(750);

    EXPECT_EQ(sourceProbe.curCycle(), Cycles(2));
    EXPECT_EQ(sourceProbe.clockEdge(), 1000);
    EXPECT_EQ(sourceProbe.nextCycle(), 1500);

    EXPECT_EQ(memoryProbe.curCycle(), Cycles(1));
    EXPECT_EQ(memoryProbe.clockEdge(), 1000);
    EXPECT_EQ(memoryProbe.nextCycle(), 2000);

    sourceProbe.sample("mid-cycle");
    memoryProbe.sample("mid-cycle");

    EXPECT_EQ(sourceProbe.trace().back(),
              "tick=750 label=source_probe tag=mid-cycle "
              "period=500 cycle=2 edge=1000 next=1500");
    EXPECT_EQ(memoryProbe.trace().back(),
              "tick=750 label=memory_probe tag=mid-cycle "
              "period=1000 cycle=1 edge=1000 next=2000");
}

TEST_F(ClockDomainsTest, DvfsChangesPeriodsAndPropagatesToDerivedClock)
{
    DomainBundle domains;
    ClockedProbe sourceProbe("source_probe", domains.sourceDomain, queue);
    ClockedProbe memoryProbe("memory_probe", domains.derivedDomain, queue);

    queue->setCurTick(750);
    EXPECT_EQ(sourceProbe.clockEdge(), 1000);
    EXPECT_EQ(memoryProbe.clockEdge(), 1000);

    domains.sourceDomain.perfLevel(1);

    EXPECT_EQ(domains.sourceDomain.perfLevel(), 1u);
    EXPECT_EQ(domains.voltageDomain.perfLevel(), 1u);
    EXPECT_DOUBLE_EQ(domains.voltageDomain.voltage(), 0.9);

    EXPECT_EQ(domains.sourceDomain.clockPeriod(), 1000);
    EXPECT_EQ(domains.derivedDomain.clockPeriod(), 2000);
    EXPECT_EQ(sourceProbe.clockUpdates(), 1u);
    EXPECT_EQ(memoryProbe.clockUpdates(), 1u);

    sourceProbe.sample("after-dvfs");
    memoryProbe.sample("after-dvfs");

    EXPECT_EQ(sourceProbe.trace().back(),
              "tick=750 label=source_probe tag=after-dvfs "
              "period=1000 cycle=2 edge=1000 next=2000");
    EXPECT_EQ(memoryProbe.trace().back(),
              "tick=750 label=memory_probe tag=after-dvfs "
              "period=2000 cycle=1 edge=1000 next=3000");
}

TEST_F(ClockDomainsTest, PulseSchedulingUsesEachProbeClockEdges)
{
    DomainBundle domains;
    ClockedProbe sourceProbe("source_probe", domains.sourceDomain, queue);
    ClockedProbe memoryProbe("memory_probe", domains.derivedDomain, queue);

    sourceProbe.schedulePulse(Cycles(1));
    memoryProbe.schedulePulse(Cycles(1));
    sourceProbe.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 1000);
    EXPECT_EQ(sourceProbe.pulsesSeen(), 1u);
    EXPECT_EQ(memoryProbe.pulsesSeen(), 1u);

    EXPECT_EQ(sourceProbe.trace().back(),
              "tick=500 label=source_probe tag=pulse-1 "
              "period=500 cycle=1 edge=500 next=1000");
    EXPECT_EQ(memoryProbe.trace().back(),
              "tick=1000 label=memory_probe tag=pulse-1 "
              "period=1000 cycle=1 edge=1000 next=2000");
}

} // namespace lesson04

} // namespace tutorial

} // namespace gem5
