// AI-generated by Codex/Claude.

#ifndef __CPU_O3_FTR_PIPEVIEW_SINK_HH__
#define __CPU_O3_FTR_PIPEVIEW_SINK_HH__

namespace gem5
{
namespace o3
{

class DynInst;

void
maybeEmitPipeviewFtr(const DynInst &inst);

} // namespace o3
} // namespace gem5

#endif
