// AI-generated by Codex/Claude.

#include "base/logging.hh"
#include "cpu/o3/ftr_pipeview_sink.hh"
#include "debug/O3PipeView.hh"

namespace gem5
{
namespace o3
{

void
maybeEmitPipeviewFtr(const DynInst &inst)
{
    if (!debug::O3PipeView)
        return;

    warn_once("O3PipeView requested, but FTR trace is unavailable in this "
              "build.");
}

} // namespace o3
} // namespace gem5
