// AI-generated by Codex/Claude.

#include "cpu/o3/ftr_pipeview_sink.hh"

#include <algorithm>
#include <cstdint>
#include <initializer_list>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <vector>

#include "base/logging.hh"
#include "base/output.hh"
#include "cpu/o3/dyn_inst.hh"
#include "debug/O3PipeView.hh"
#include "ftr/ftr_writer.h"
#include "sim/core.hh"

namespace gem5
{
namespace o3
{
namespace
{
using StreamName = std::string;
using StreamId = uint64_t;
using TxId = uint64_t;

Tick
toAbsTick(Tick fetch_tick, int32_t relative_tick)
{
    return relative_tick == -1 ? 0 : fetch_tick + relative_tick;
}

Tick
maxNonZero(const std::initializer_list<Tick> &ticks)
{
    Tick max_tick = 0;
    for (auto tick : ticks)
        max_tick = std::max(max_tick, tick);
    return max_tick;
}

class PipeviewFtrSink
{
  public:
    ~PipeviewFtrSink()
    {
        flush();
    }

    void emit(const DynInst &inst)
    {
        if (!debug::O3PipeView || inst.fetchTick == Tick(-1))
            return;

        std::lock_guard<std::mutex> lock(locker);
        ensureWriterLocked();
        if (!writer)
            return;

        const Tick fetch_tick = inst.fetchTick;
        const Tick tick_fetch = fetch_tick;
        const Tick tick_decode = toAbsTick(fetch_tick, inst.decodeTick);
        const Tick tick_rename = toAbsTick(fetch_tick, inst.renameTick);
        const Tick tick_dispatch = toAbsTick(fetch_tick, inst.dispatchTick);
        const Tick tick_issue = toAbsTick(fetch_tick, inst.issueTick);
        const Tick tick_complete = toAbsTick(fetch_tick, inst.completeTick);
        const Tick tick_retire = toAbsTick(fetch_tick, inst.commitTick);
        const Tick tick_store = toAbsTick(fetch_tick, inst.storeTick);
        const Tick end_tick = tick_retire != 0
            ? tick_retire
            : maxNonZero({tick_fetch, tick_decode, tick_rename,
                          tick_dispatch, tick_issue, tick_complete,
                          tick_store});

        const StreamName stream_name = inst.cpu->name() + ":" +
            std::to_string(inst.threadNumber);
        const StreamId stream_id = getStreamIdLocked(stream_name);
        const TxId local_id = nextTxId[stream_id]++;
        const TxId tx_id = (stream_id << 48) | local_id;
        const bool retired = !inst.isSquashed() && (tick_retire != 0);
        const bool squashed = !retired;

        writer->startTransaction(tx_id, stream_id, stream_id, tick_fetch);
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "cpu_name",
                               ftr::data_type::STRING, inst.cpu->name());
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "hart_id",
                               ftr::data_type::UNSIGNED,
                               static_cast<uint64_t>(inst.threadNumber));
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "seq_num",
                               ftr::data_type::UNSIGNED,
                               static_cast<uint64_t>(inst.seqNum));
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "pc",
                               ftr::data_type::UNSIGNED,
                               inst.pcState().instAddr());
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "upc",
                               ftr::data_type::UNSIGNED,
                               inst.pcState().microPC());
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "disasm",
                               ftr::data_type::STRING,
                               inst.staticInst->disassemble(
                                   inst.pcState().instAddr()));
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "is_load",
                               ftr::data_type::BOOLEAN, inst.isLoad());
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "is_store",
                               ftr::data_type::BOOLEAN, inst.isStore());
        writer->writeAttribute(tx_id, ftr::event_type::BEGIN, "is_control",
                               ftr::data_type::BOOLEAN, inst.isControl());

        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_fetch",
                               ftr::data_type::TIME, tick_fetch);
        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_decode",
                               ftr::data_type::TIME, tick_decode);
        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_rename",
                               ftr::data_type::TIME, tick_rename);
        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_dispatch",
                               ftr::data_type::TIME, tick_dispatch);
        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_issue",
                               ftr::data_type::TIME, tick_issue);
        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_complete",
                               ftr::data_type::TIME, tick_complete);
        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_retire",
                               ftr::data_type::TIME, tick_retire);
        writer->writeAttribute(tx_id, ftr::event_type::RECORD, "tick_store",
                               ftr::data_type::TIME, tick_store);

        writer->writeAttribute(tx_id, ftr::event_type::END, "retired",
                               ftr::data_type::BOOLEAN, retired);
        writer->writeAttribute(tx_id, ftr::event_type::END, "squashed",
                               ftr::data_type::BOOLEAN, squashed);
        writer->endTransaction(tx_id, end_tick);
    }

  private:
    void ensureWriterLocked()
    {
        if (writer)
            return;

        writer = std::make_unique<ftr::ftr_writer<true>>(
            simout.resolve("trace.ftr"));
        writer->writeInfo(-12);
        if (sim_clock::Frequency != 1'000'000'000'000ULL)
            warn_once("O3PipeView output tick frequency is not 1e12; FTR "
                      "time units in trace.ftr are approximate.");
    }

    StreamId getStreamIdLocked(const StreamName &name)
    {
        const auto stream_it = streamIds.find(name);
        if (stream_it != streamIds.end())
            return stream_it->second;

        const StreamId id = nextStreamId++;
        streamIds[name] = id;
        nextTxId.resize(id + 1, 0);
        writer->writeStream(id, name, "o3");
        writer->writeGenerator(id, "o3", id);
        return id;
    }

    void flush()
    {
        std::lock_guard<std::mutex> lock(locker);
        writer.reset();
    }

    std::mutex locker;
    std::unique_ptr<ftr::ftr_writer<true>> writer;
    StreamId nextStreamId = 0;
    std::unordered_map<StreamName, StreamId> streamIds;
    std::vector<uint64_t> nextTxId;
};

PipeviewFtrSink &
pipeviewFtrSink()
{
    static PipeviewFtrSink sink;
    return sink;
}
}

void
maybeEmitPipeviewFtr(const DynInst &inst)
{
    pipeviewFtrSink().emit(inst);
}

} // namespace o3
} // namespace gem5
