# Copyright (c) 2026 ripopov
# SPDX-License-Identifier: BSD-3-Clause

Import('*')

if not env['CONF']['USE_SYSTEMC']:
    Return()

SimObject('ChiDrivers.py', sim_objects=[
    'ChiEventBus',
    'ChiFinishBarrier',
    'ChiTileSlot',
    'ChiDriverBase',
    'IdleDriver',
    'SmokeReadDriver',
    'SmokeWriteDriver',
    'SmokeOpcodeMixDriver',
    'PingPongDriver',
    'FalseSharingDriver',
    'MemcpyDriver',
    'MemsetDriver',
    'OpcodeWalkDriver',
])

Source('driver_base.cc')
Source('event_bus.cc')
Source('false_sharing.cc')
Source('finish_barrier.cc')
Source('idle_driver.cc')
Source('memcpy_driver.cc')
Source('memset_driver.cc')
Source('opcode_walk.cc')
Source('ping_pong.cc')
Source('smoke_read.cc')
Source('smoke_write.cc')
Source('smoke_opcode_mix.cc')
Source('tile_slot.cc')

DebugFlag('ChiTestbench')
