/* AI-generated by Codex/Claude. */

#ifndef __TUTORIAL_LESSON02_SIMOBJECT_LIFECYCLE_HH__
#define __TUTORIAL_LESSON02_SIMOBJECT_LIFECYCLE_HH__

#include <cstdint>
#include <string>
#include <vector>

#include "params/TutorialLifecycleDemo.hh"
#include "sim/sim_object.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson02
{

/**
 * A small SimObject used by Lesson 2 to demonstrate lifecycle hooks.
 *
 * The object records lifecycle hook invocations and schedules a repeating
 * callback from startup(). drain()/drainResume() preserve an in-flight event
 * to demonstrate how objects pause and resume cleanly.
 */
class TutorialLifecycleDemo : public SimObject
{
  public:
    PARAMS(TutorialLifecycleDemo);
    explicit TutorialLifecycleDemo(const Params &p);

    void init() override;
    void initState() override;
    void startup() override;
    DrainState drain() override;
    void drainResume() override;

    void serviceOne();
    void runToCompletion();

    bool hasScheduledPulse() const { return pulseEvent.scheduled(); }
    Tick nextPulseTick() const { return pulseEvent.when(); }

    const std::vector<std::string> &lifecycleTrace() const
    {
        return lifecycleLog;
    }

    const std::vector<std::string> &callbackTrace() const
    {
        return callbackLog;
    }

    std::uint64_t pulsesExecuted() const { return executedPulses; }

  private:
    void appendLifecycle(const std::string &hook);
    void appendCallback(const std::string &label);
    void onPulse();

    Tick startupDelay;
    const Tick pulseInterval = 2;
    unsigned remainingPulses;
    std::uint64_t executedPulses = 0;

    bool deferredByDrain = false;
    Tick deferredTick = 0;

    std::vector<std::string> lifecycleLog;
    std::vector<std::string> callbackLog;

    EventFunctionWrapper pulseEvent;
};

} // namespace lesson02

} // namespace tutorial

} // namespace gem5

#endif // __TUTORIAL_LESSON02_SIMOBJECT_LIFECYCLE_HH__
