/* AI-generated by Codex/Claude. */

#include "tutorial/lesson02/simobject_lifecycle.hh"

#include <sstream>

#include "sim/cur_tick.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson02
{

TutorialLifecycleDemo::TutorialLifecycleDemo(const Params &p)
    : SimObject(p),
      startupDelay(p.startup_delay),
      remainingPulses(p.pulse_count),
      pulseEvent([this]() { onPulse(); }, name() + ".pulse_event")
{
    std::ostringstream details;
    details << "construct startup_delay=" << startupDelay
            << " pulse_count=" << p.pulse_count;
    appendLifecycle(details.str());
}

void
TutorialLifecycleDemo::init()
{
    appendLifecycle("init");
}

void
TutorialLifecycleDemo::initState()
{
    appendLifecycle("initState");
}

void
TutorialLifecycleDemo::startup()
{
    appendLifecycle("startup");

    if (remainingPulses > 0 && !pulseEvent.scheduled()) {
        schedule(pulseEvent, curTick() + startupDelay);
    }
}

DrainState
TutorialLifecycleDemo::drain()
{
    appendLifecycle("drain");

    if (pulseEvent.scheduled()) {
        deferredTick = pulseEvent.when();
        deferredByDrain = true;
        deschedule(pulseEvent);
    }

    return DrainState::Drained;
}

void
TutorialLifecycleDemo::drainResume()
{
    appendLifecycle("drainResume");

    if (deferredByDrain) {
        schedule(pulseEvent, deferredTick);
        deferredByDrain = false;
    }
}

void
TutorialLifecycleDemo::serviceOne()
{
    eventQueue()->serviceOne();
}

void
TutorialLifecycleDemo::runToCompletion()
{
    while (!eventQueue()->empty()) {
        eventQueue()->serviceOne();
    }
}

void
TutorialLifecycleDemo::appendLifecycle(const std::string &hook)
{
    std::ostringstream entry;
    entry << "tick=" << curTick() << " hook=" << hook;
    lifecycleLog.push_back(entry.str());
}

void
TutorialLifecycleDemo::appendCallback(const std::string &label)
{
    std::ostringstream entry;
    entry << "tick=" << curTick() << " label=" << label;
    callbackLog.push_back(entry.str());
}

void
TutorialLifecycleDemo::onPulse()
{
    executedPulses++;
    remainingPulses--;

    std::ostringstream label;
    label << "pulse-" << executedPulses;
    appendCallback(label.str());

    if (remainingPulses > 0) {
        schedule(pulseEvent, curTick() + pulseInterval);
    }
}

} // namespace lesson02

} // namespace tutorial

} // namespace gem5
