/* AI-generated by Codex/Claude. */

#include <gtest/gtest.h>

#include <string>
#include <vector>

#include "params/TutorialLifecycleDemo.hh"
#include "sim/eventq.hh"
#include "tutorial/lesson02/simobject_lifecycle.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson02
{

class TutorialLifecycleDemoTest : public ::testing::Test
{
  protected:
    EventQueue *queue = nullptr;
    EventQueue *savedQueue = nullptr;

    void
    SetUp() override
    {
        queue = getEventQueue(0);
        savedQueue = curEventQueue();
        curEventQueue(queue);

        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
    }

    void
    TearDown() override
    {
        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
        curEventQueue(savedQueue);
    }
};

TEST_F(TutorialLifecycleDemoTest, RunsLifecycleAndCallbacksInOrder)
{
    TutorialLifecycleDemoParams params;
    params.name = "tutorial.lesson02.demo";
    params.eventq_index = 0;
    params.startup_delay = 4;
    params.pulse_count = 3;

    TutorialLifecycleDemo demo(params);

    demo.init();
    demo.initState();
    demo.startup();
    demo.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 8);
    EXPECT_EQ(demo.pulsesExecuted(), 3);

    const std::vector<std::string> expectedLifecycle = {
        "tick=0 hook=construct startup_delay=4 pulse_count=3",
        "tick=0 hook=init",
        "tick=0 hook=initState",
        "tick=0 hook=startup",
    };

    const std::vector<std::string> expectedCallbacks = {
        "tick=4 label=pulse-1",
        "tick=6 label=pulse-2",
        "tick=8 label=pulse-3",
    };

    EXPECT_EQ(demo.lifecycleTrace(), expectedLifecycle);
    EXPECT_EQ(demo.callbackTrace(), expectedCallbacks);
}

TEST_F(TutorialLifecycleDemoTest, DrainResumeRestoresDeferredEvent)
{
    TutorialLifecycleDemoParams params;
    params.name = "tutorial.lesson02.drain_demo";
    params.eventq_index = 0;
    params.startup_delay = 4;
    params.pulse_count = 4;

    TutorialLifecycleDemo demo(params);

    demo.init();
    demo.initState();
    demo.startup();

    demo.serviceOne();
    EXPECT_EQ(queue->getCurTick(), 4);
    EXPECT_TRUE(demo.hasScheduledPulse());
    EXPECT_EQ(demo.nextPulseTick(), 6);

    EXPECT_EQ(demo.drain(), DrainState::Drained);
    EXPECT_FALSE(demo.hasScheduledPulse());
    EXPECT_TRUE(queue->empty());

    demo.drainResume();
    EXPECT_TRUE(demo.hasScheduledPulse());
    EXPECT_EQ(demo.nextPulseTick(), 6);

    demo.runToCompletion();

    EXPECT_EQ(queue->getCurTick(), 10);
    EXPECT_EQ(demo.pulsesExecuted(), 4);

    const std::vector<std::string> expectedLifecycle = {
        "tick=0 hook=construct startup_delay=4 pulse_count=4",
        "tick=0 hook=init",
        "tick=0 hook=initState",
        "tick=0 hook=startup",
        "tick=4 hook=drain",
        "tick=4 hook=drainResume",
    };

    const std::vector<std::string> expectedCallbacks = {
        "tick=4 label=pulse-1",
        "tick=6 label=pulse-2",
        "tick=8 label=pulse-3",
        "tick=10 label=pulse-4",
    };

    EXPECT_EQ(demo.lifecycleTrace(), expectedLifecycle);
    EXPECT_EQ(demo.callbackTrace(), expectedCallbacks);
}

} // namespace lesson02

} // namespace tutorial

} // namespace gem5
