# AI-generated by Codex/Claude.

from m5.params import Param
from m5.SimObject import SimObject


class TutorialLifecycleDemo(SimObject):
    type = "TutorialLifecycleDemo"
    cxx_header = "tutorial/lesson02/simobject_lifecycle.hh"
    cxx_class = "gem5::tutorial::lesson02::TutorialLifecycleDemo"

    startup_delay = Param.Tick(
        4,
        "Ticks between startup() and first callback",
    )
    pulse_count = Param.Unsigned(
        3,
        "Number of callbacks emitted by the demo",
    )
