/* AI-generated by Codex/Claude. */

#include <gtest/gtest.h>

#include <string>
#include <vector>

#include "params/DerivedClockDomain.hh"
#include "params/SrcClockDomain.hh"
#include "params/TutorialClockedObjectDemo.hh"
#include "params/VoltageDomain.hh"
#include "sim/clock_domain.hh"
#include "sim/eventq.hh"
#include "sim/voltage_domain.hh"
#include "tutorial/lesson05/clocked_objects.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson05
{

class TutorialClockedObjectDemoTest : public ::testing::Test
{
  protected:
    EventQueue *queue = nullptr;
    EventQueue *savedQueue = nullptr;

    void
    SetUp() override
    {
        queue = getEventQueue(0);
        savedQueue = curEventQueue();
        curEventQueue(queue);

        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
    }

    void
    TearDown() override
    {
        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
        curEventQueue(savedQueue);
    }
};

struct DomainBundle
{
    static VoltageDomainParams
    makeVoltageParams()
    {
        VoltageDomainParams params;
        params.name = "tutorial.lesson05.vdd";
        params.eventq_index = 0;
        params.voltage = {1.0, 0.9};
        return params;
    }

    static SrcClockDomainParams
    makeSourceParams(VoltageDomain *voltage_domain)
    {
        SrcClockDomainParams params;
        params.name = "tutorial.lesson05.src_clk";
        params.eventq_index = 0;
        params.clock = {500, 1000};
        params.domain_id = 5;
        params.init_perf_level = 0;
        params.voltage_domain = voltage_domain;
        return params;
    }

    static DerivedClockDomainParams
    makeDerivedParams(ClockDomain *parent_domain)
    {
        DerivedClockDomainParams params;
        params.name = "tutorial.lesson05.mem_clk";
        params.eventq_index = 0;
        params.clk_divider = 2;
        params.clk_domain = parent_domain;
        return params;
    }

    VoltageDomainParams voltageParams;
    VoltageDomain voltageDomain;
    SrcClockDomainParams sourceParams;
    SrcClockDomain sourceDomain;
    DerivedClockDomainParams derivedParams;
    DerivedClockDomain derivedDomain;

    DomainBundle()
        : voltageParams(makeVoltageParams()),
          voltageDomain(voltageParams),
          sourceParams(makeSourceParams(&voltageDomain)),
          sourceDomain(sourceParams),
          derivedParams(makeDerivedParams(&sourceDomain)),
          derivedDomain(derivedParams)
    {
    }
};

TutorialClockedObjectDemoParams
makeDemoParams(const std::string &name,
               ClockDomain *clock_domain,
               unsigned startup_cycles,
               unsigned pulse_count,
               unsigned pulse_stride_cycles)
{
    TutorialClockedObjectDemoParams params;
    params.name = name;
    params.eventq_index = 0;
    params.clk_domain = clock_domain;
    params.power_state = nullptr;
    params.startup_cycles = startup_cycles;
    params.pulse_count = pulse_count;
    params.pulse_stride_cycles = pulse_stride_cycles;
    return params;
}

TEST_F(TutorialClockedObjectDemoTest, ClockHelpersExposeCycleTickConversions)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson05.source", &domains.sourceDomain,
        2, 3, 1);
    TutorialClockedObjectDemo demo(params);

    EXPECT_EQ(demo.clockPeriod(), 500);
    EXPECT_EQ(demo.clockEdge(), 0);
    EXPECT_EQ(demo.clockEdge(Cycles(3)), 1500);
    EXPECT_EQ(demo.cyclesToTicks(Cycles(4)), 2000);
    EXPECT_EQ(demo.ticksToCycles(501), Cycles(2));

    queue->setCurTick(750);

    EXPECT_EQ(demo.curCycle(), Cycles(2));
    EXPECT_EQ(demo.clockEdge(), 1000);
    EXPECT_EQ(demo.nextCycle(), 1500);

    demo.sample("mid-cycle");
    EXPECT_EQ(demo.timingTrace().back(),
              "tick=750 name=tutorial.lesson05.source tag=mid-cycle "
              "period=500 cycle=2 edge=1000 next=1500");
}

TEST_F(TutorialClockedObjectDemoTest, StartupSchedulesCycleAlignedPulses)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson05.startup", &domains.sourceDomain,
        2, 3, 1);
    TutorialClockedObjectDemo demo(params);

    demo.init();
    demo.startup();

    EXPECT_TRUE(demo.hasScheduledPulse());
    EXPECT_EQ(demo.nextPulseTick(), 1000);
    EXPECT_EQ(demo.cyclesUntilNextPulse(), Cycles(2));

    demo.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 2000);
    EXPECT_EQ(demo.pulsesSeen(), 3u);

    const std::vector<std::string> expectedLifecycle = {
        "tick=0 hook=construct startup_cycles=2 pulse_count=3 "
        "pulse_stride_cycles=1",
        "tick=0 hook=init",
        "tick=0 hook=startup",
    };

    const std::vector<std::string> expectedTiming = {
        "tick=1000 name=tutorial.lesson05.startup tag=pulse-1 "
        "period=500 cycle=2 edge=1000 next=1500",
        "tick=1500 name=tutorial.lesson05.startup tag=pulse-2 "
        "period=500 cycle=3 edge=1500 next=2000",
        "tick=2000 name=tutorial.lesson05.startup tag=pulse-3 "
        "period=500 cycle=4 edge=2000 next=2500",
    };

    EXPECT_EQ(demo.lifecycleTrace(), expectedLifecycle);
    EXPECT_EQ(demo.timingTrace(), expectedTiming);
}

TEST_F(TutorialClockedObjectDemoTest, ExplicitClockDomainsChangePulseTicks)
{
    DomainBundle domains;
    auto sourceParams = makeDemoParams(
        "tutorial.lesson05.cpu", &domains.sourceDomain,
        0, 1, 1);
    auto memoryParams = makeDemoParams(
        "tutorial.lesson05.mem", &domains.derivedDomain,
        0, 1, 1);

    TutorialClockedObjectDemo source(sourceParams);
    TutorialClockedObjectDemo memory(memoryParams);

    source.schedulePulse(Cycles(1));
    memory.schedulePulse(Cycles(1));
    source.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 1000);
    EXPECT_EQ(source.pulsesSeen(), 1u);
    EXPECT_EQ(memory.pulsesSeen(), 1u);

    EXPECT_EQ(source.timingTrace().back(),
              "tick=500 name=tutorial.lesson05.cpu tag=pulse-1 "
              "period=500 cycle=1 edge=500 next=1000");
    EXPECT_EQ(memory.timingTrace().back(),
              "tick=1000 name=tutorial.lesson05.mem tag=pulse-1 "
              "period=1000 cycle=1 edge=1000 next=2000");
}

TEST_F(TutorialClockedObjectDemoTest, DvfsUpdatesMembersAndChangesScheduling)
{
    DomainBundle domains;
    auto sourceParams = makeDemoParams(
        "tutorial.lesson05.cpu", &domains.sourceDomain,
        0, 1, 1);
    auto memoryParams = makeDemoParams(
        "tutorial.lesson05.mem", &domains.derivedDomain,
        0, 1, 1);

    TutorialClockedObjectDemo source(sourceParams);
    TutorialClockedObjectDemo memory(memoryParams);

    queue->setCurTick(750);
    domains.sourceDomain.perfLevel(1);

    EXPECT_EQ(domains.sourceDomain.perfLevel(), 1u);
    EXPECT_EQ(domains.voltageDomain.perfLevel(), 1u);
    EXPECT_DOUBLE_EQ(domains.voltageDomain.voltage(), 0.9);

    EXPECT_EQ(domains.sourceDomain.clockPeriod(), 1000);
    EXPECT_EQ(domains.derivedDomain.clockPeriod(), 2000);
    EXPECT_EQ(source.clockUpdates(), 1u);
    EXPECT_EQ(memory.clockUpdates(), 1u);

    source.sample("after-dvfs");
    memory.sample("after-dvfs");

    EXPECT_EQ(source.timingTrace().back(),
              "tick=750 name=tutorial.lesson05.cpu tag=after-dvfs "
              "period=1000 cycle=2 edge=1000 next=2000");
    EXPECT_EQ(memory.timingTrace().back(),
              "tick=750 name=tutorial.lesson05.mem tag=after-dvfs "
              "period=2000 cycle=1 edge=1000 next=3000");

    source.schedulePulse(Cycles(1));
    memory.schedulePulse(Cycles(1));
    source.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 3000);

    EXPECT_EQ(source.timingTrace().back(),
              "tick=2000 name=tutorial.lesson05.cpu tag=pulse-1 "
              "period=1000 cycle=3 edge=2000 next=3000");
    EXPECT_EQ(memory.timingTrace().back(),
              "tick=3000 name=tutorial.lesson05.mem tag=pulse-1 "
              "period=2000 cycle=2 edge=3000 next=5000");
}

} // namespace lesson05

} // namespace tutorial

} // namespace gem5
