/* AI-generated by Codex/Claude. */

#ifndef __TUTORIAL_LESSON05_CLOCKED_OBJECTS_HH__
#define __TUTORIAL_LESSON05_CLOCKED_OBJECTS_HH__

#include <cstdint>
#include <string>
#include <vector>

#include "params/TutorialClockedObjectDemo.hh"
#include "sim/clocked_object.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson05
{

/**
 * A small ClockedObject used by Lesson 5 to demonstrate clock-aware
 * scheduling and cycle/tick conversion helpers.
 */
class TutorialClockedObjectDemo : public ClockedObject
{
  public:
    PARAMS(TutorialClockedObjectDemo);
    explicit TutorialClockedObjectDemo(const Params &p);

    void init() override;
    void startup() override;

    void sample(const std::string &tag);
    void schedulePulse(Cycles cycles_from_now);
    void serviceOne();
    void runToCompletion();

    bool hasScheduledPulse() const { return pulseEvent.scheduled(); }
    Tick nextPulseTick() const { return pulseEvent.when(); }
    Cycles cyclesUntilNextPulse() const;

    const std::vector<std::string> &lifecycleTrace() const
    {
        return lifecycleLog;
    }

    const std::vector<std::string> &timingTrace() const
    {
        return timingLog;
    }

    std::uint64_t pulsesSeen() const { return pulseCount; }
    std::uint64_t clockUpdates() const { return clockUpdateCount; }

  private:
    void appendLifecycle(const std::string &hook);
    void appendTiming(const std::string &tag);
    void onPulse();
    void clockPeriodUpdated() override;

    const Cycles startupDelayCycles;
    const Cycles pulseStrideCycles;
    unsigned remainingPulses;

    std::uint64_t pulseCount = 0;
    std::uint64_t clockUpdateCount = 0;

    std::vector<std::string> lifecycleLog;
    std::vector<std::string> timingLog;

    EventFunctionWrapper pulseEvent;
};

} // namespace lesson05

} // namespace tutorial

} // namespace gem5

#endif // __TUTORIAL_LESSON05_CLOCKED_OBJECTS_HH__
