/* AI-generated by Codex/Claude. */

#include "tutorial/lesson05/clocked_objects.hh"

#include <sstream>

#include "base/logging.hh"
#include "sim/cur_tick.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson05
{

TutorialClockedObjectDemo::TutorialClockedObjectDemo(const Params &p)
    : ClockedObject(p),
      startupDelayCycles(Cycles(p.startup_cycles)),
      pulseStrideCycles(Cycles(p.pulse_stride_cycles)),
      remainingPulses(p.pulse_count),
      pulseEvent([this]() { onPulse(); }, name() + ".pulse_event")
{
    fatal_if(p.pulse_stride_cycles == 0,
             "%s pulse_stride_cycles must be >= 1", name());

    std::ostringstream details;
    details << "construct startup_cycles=" << startupDelayCycles
            << " pulse_count=" << p.pulse_count
            << " pulse_stride_cycles=" << pulseStrideCycles;
    appendLifecycle(details.str());
}

void
TutorialClockedObjectDemo::init()
{
    appendLifecycle("init");
}

void
TutorialClockedObjectDemo::startup()
{
    appendLifecycle("startup");

    if (remainingPulses > 0 && !pulseEvent.scheduled()) {
        schedulePulse(startupDelayCycles);
    }
}

void
TutorialClockedObjectDemo::sample(const std::string &tag)
{
    appendTiming(tag);
}

void
TutorialClockedObjectDemo::schedulePulse(Cycles cycles_from_now)
{
    if (pulseEvent.scheduled()) {
        deschedule(pulseEvent);
    }

    const Tick target_tick = clockEdge() + cyclesToTicks(cycles_from_now);
    schedule(pulseEvent, target_tick);
}

void
TutorialClockedObjectDemo::serviceOne()
{
    eventQueue()->serviceOne();
}

void
TutorialClockedObjectDemo::runToCompletion()
{
    while (!eventQueue()->empty()) {
        eventQueue()->serviceOne();
    }
}

Cycles
TutorialClockedObjectDemo::cyclesUntilNextPulse() const
{
    if (!pulseEvent.scheduled()) {
        return Cycles(0);
    }

    return ticksToCycles(pulseEvent.when() - curTick());
}

void
TutorialClockedObjectDemo::appendLifecycle(const std::string &hook)
{
    std::ostringstream entry;
    entry << "tick=" << curTick() << " hook=" << hook;
    lifecycleLog.push_back(entry.str());
}

void
TutorialClockedObjectDemo::appendTiming(const std::string &tag)
{
    std::ostringstream line;
    line << "tick=" << curTick()
         << " name=" << name()
         << " tag=" << tag
         << " period=" << clockPeriod()
         << " cycle=" << curCycle()
         << " edge=" << clockEdge()
         << " next=" << nextCycle();
    timingLog.push_back(line.str());
}

void
TutorialClockedObjectDemo::onPulse()
{
    pulseCount++;
    remainingPulses--;

    std::ostringstream tag;
    tag << "pulse-" << pulseCount;
    appendTiming(tag.str());

    if (remainingPulses > 0) {
        schedulePulse(pulseStrideCycles);
    }
}

void
TutorialClockedObjectDemo::clockPeriodUpdated()
{
    clockUpdateCount++;

    std::ostringstream tag;
    tag << "clock-period-updated-" << clockUpdateCount;
    appendTiming(tag.str());
}

} // namespace lesson05

} // namespace tutorial

} // namespace gem5
