/* AI-generated by Codex/Claude. */

#include "sim/power/power_model.hh"

namespace gem5
{

void
PowerModel::setClockedObject(ClockedObject *clkobj)
{
    clocked_object = clkobj;

    for (auto &state: states_pm) {
        state->setClockedObject(clkobj);
    }
}

} // namespace gem5
