# AI-generated by Codex/Claude.

from m5.objects.ClockedObject import ClockedObject
from m5.params import Param


class TutorialClockedObjectDemo(ClockedObject):
    type = "TutorialClockedObjectDemo"
    cxx_header = "tutorial/lesson05/clocked_objects.hh"
    cxx_class = "gem5::tutorial::lesson05::TutorialClockedObjectDemo"

    startup_cycles = Param.Unsigned(
        2,
        "Cycles from startup() to the first pulse event",
    )
    pulse_count = Param.Unsigned(
        3,
        "Number of pulse callbacks emitted by this demo",
    )
    pulse_stride_cycles = Param.Unsigned(
        1,
        "Cycles between consecutive pulse callbacks",
    )
