# -*- mode:python -*-

Import('*')

if not env['CONF']['USE_JITCPU']:
    Return()

if not env['CONF']['USE_RISCV_ISA']:
    Return()

env.TagImplies('jitcpu', 'gem5 lib')
env.TagImplies('jitcpu', 'riscv isa')

SimObject('RiscvJitCPU.py', sim_objects=['RiscvJitCPU'], tags=['jitcpu'])
Source('riscv_jit_cpu.cc', tags=['jitcpu'])

DebugFlag('JitCPU', 'RISC-V QEMU/TCG JitCPU execution', tags=['jitcpu'])

env.Append(LIBS=['dl'])
