/* AI-generated by Codex/Claude. */

#include <gtest/gtest.h>

#include <sstream>
#include <string>
#include <vector>

#include "base/debug.hh"
#include "base/gtest/logging.hh"
#include "base/trace.hh"
#include "params/DerivedClockDomain.hh"
#include "params/SrcClockDomain.hh"
#include "params/TutorialStatsDebugDemo.hh"
#include "params/VoltageDomain.hh"
#include "sim/clock_domain.hh"
#include "sim/eventq.hh"
#include "sim/voltage_domain.hh"
#include "tutorial/lesson07/stats_debug_logging.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson07
{

class TutorialStatsDebugDemoTest : public ::testing::Test
{
  protected:
    EventQueue *queue = nullptr;
    EventQueue *savedQueue = nullptr;

    void
    SetUp() override
    {
        queue = getEventQueue(0);
        savedQueue = curEventQueue();
        curEventQueue(queue);

        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
    }

    void
    TearDown() override
    {
        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
        curEventQueue(savedQueue);

        debug::changeFlag("TutorialLesson07", false);
        debug::changeFlag("FmtFlag", false);
        trace::disable();
    }
};

struct DomainBundle
{
    static VoltageDomainParams
    makeVoltageParams()
    {
        VoltageDomainParams params;
        params.name = "tutorial.lesson07.vdd";
        params.eventq_index = 0;
        params.voltage = {1.0, 0.9};
        return params;
    }

    static SrcClockDomainParams
    makeSourceParams(VoltageDomain *voltage_domain)
    {
        SrcClockDomainParams params;
        params.name = "tutorial.lesson07.src_clk";
        params.eventq_index = 0;
        params.clock = {500, 1000};
        params.domain_id = 7;
        params.init_perf_level = 0;
        params.voltage_domain = voltage_domain;
        return params;
    }

    static DerivedClockDomainParams
    makeDerivedParams(ClockDomain *parent_domain)
    {
        DerivedClockDomainParams params;
        params.name = "tutorial.lesson07.mem_clk";
        params.eventq_index = 0;
        params.clk_divider = 2;
        params.clk_domain = parent_domain;
        return params;
    }

    VoltageDomainParams voltageParams;
    VoltageDomain voltageDomain;
    SrcClockDomainParams sourceParams;
    SrcClockDomain sourceDomain;
    DerivedClockDomainParams derivedParams;
    DerivedClockDomain derivedDomain;

    DomainBundle()
        : voltageParams(makeVoltageParams()),
          voltageDomain(voltageParams),
          sourceParams(makeSourceParams(&voltageDomain)),
          sourceDomain(sourceParams),
          derivedParams(makeDerivedParams(&sourceDomain)),
          derivedDomain(derivedParams)
    {
    }
};

TutorialStatsDebugDemoParams
makeDemoParams(const std::string &name,
               ClockDomain *clock_domain,
               unsigned issue_count,
               unsigned issue_start_cycles,
               unsigned issue_stride_cycles,
               unsigned base_latency_cycles,
               unsigned latency_spread_cycles,
               unsigned drop_every)
{
    TutorialStatsDebugDemoParams params;
    params.name = name;
    params.eventq_index = 0;
    params.clk_domain = clock_domain;
    params.power_state = nullptr;
    params.issue_count = issue_count;
    params.issue_start_cycles = issue_start_cycles;
    params.issue_stride_cycles = issue_stride_cycles;
    params.base_latency_cycles = base_latency_cycles;
    params.latency_spread_cycles = latency_spread_cycles;
    params.drop_every = drop_every;
    return params;
}

TEST_F(TutorialStatsDebugDemoTest, StatsHierarchyTracksAcceptedTraffic)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson07.stats",
        &domains.sourceDomain,
        4,
        1,
        1,
        1,
        2,
        0);

    TutorialStatsDebugDemo demo(params);

    demo.init();
    demo.startup();
    demo.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 3000);

    EXPECT_EQ(demo.attempts(), 4u);
    EXPECT_EQ(demo.accepted(), 4u);
    EXPECT_EQ(demo.dropped(), 0u);
    EXPECT_DOUBLE_EQ(demo.acceptanceRatio(), 1.0);

    EXPECT_EQ(demo.completions(), 4u);
    EXPECT_EQ(demo.latencySamples(), 4u);
    EXPECT_EQ(demo.latencyCycleTotal(), 7u);
    EXPECT_DOUBLE_EQ(demo.averageLatencyCycles(), 1.75);
    EXPECT_EQ(demo.shortCompletions(), 2u);
    EXPECT_EQ(demo.longCompletions(), 2u);
    EXPECT_FALSE(demo.latencyDistributionEmpty());

    EXPECT_NE(demo.resolveStat("flow.attempts"), nullptr);
    EXPECT_NE(demo.resolveStat("flow.acceptanceRatio"), nullptr);
    EXPECT_NE(demo.resolveStat("timing.latencyCycles"), nullptr);
}

TEST_F(TutorialStatsDebugDemoTest, LoggingAndResetPathsAreObservable)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson07.logging",
        &domains.sourceDomain,
        5,
        1,
        1,
        1,
        1,
        2);

    TutorialStatsDebugDemo demo(params);

    demo.init();
    demo.startup();
    demo.runToCompletion();

    EXPECT_EQ(demo.attempts(), 5u);
    EXPECT_EQ(demo.accepted(), 3u);
    EXPECT_EQ(demo.dropped(), 2u);
    EXPECT_EQ(demo.completions(), 3u);
    EXPECT_EQ(demo.latencySamples(), 3u);

    const std::string logs = gtestLogOutput.str();
    EXPECT_NE(logs.find("info: tutorial.lesson07.logging startup"),
              std::string::npos);
    EXPECT_NE(logs.find("warn: tutorial.lesson07.logging drop token=2"),
              std::string::npos);
    EXPECT_NE(logs.find("warn: tutorial.lesson07.logging drop token=4"),
              std::string::npos);

    demo.resetObservabilityStats();

    EXPECT_EQ(demo.attempts(), 0u);
    EXPECT_EQ(demo.accepted(), 0u);
    EXPECT_EQ(demo.dropped(), 0u);
    EXPECT_EQ(demo.completions(), 0u);
    EXPECT_EQ(demo.latencySamples(), 0u);
    EXPECT_EQ(demo.latencyCycleTotal(), 0u);
    EXPECT_EQ(demo.shortCompletions(), 0u);
    EXPECT_EQ(demo.longCompletions(), 0u);
    EXPECT_EQ(demo.clockUpdates(), 0u);
    EXPECT_TRUE(demo.latencyDistributionEmpty());
}

TEST_F(TutorialStatsDebugDemoTest, DebugFlagControlsDprintfVisibility)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson07.debug",
        &domains.sourceDomain,
        0,
        1,
        1,
        1,
        0,
        0);

    TutorialStatsDebugDemo demo(params);

    std::stringstream debugStream;
    trace::setDebugLogger(new trace::OstreamLogger(debugStream));

    trace::disable();
    EXPECT_TRUE(debug::changeFlag("TutorialLesson07", false));

    demo.emitDebugProbe("disabled");
    EXPECT_EQ(debugStream.str(), "");

    debugStream.str("");
    debugStream.clear();

    trace::enable();
    EXPECT_TRUE(debug::changeFlag("FmtFlag", true));
    EXPECT_TRUE(debug::changeFlag("TutorialLesson07", true));

    demo.emitDebugProbe("enabled");

#if TRACING_ON
    const std::string debugLog = debugStream.str();
    EXPECT_NE(debugLog.find("TutorialLesson07"), std::string::npos);
    EXPECT_NE(debugLog.find("probe tag=enabled"), std::string::npos);
    EXPECT_NE(debugLog.find("probe-by-object tag=enabled"), std::string::npos);
#else
    EXPECT_EQ(debugStream.str(), "");
#endif
}

} // namespace lesson07

} // namespace tutorial

} // namespace gem5
