/* AI-generated by Codex/Claude. */

#include "tutorial/lesson07/stats_debug_logging.hh"

#include <sstream>
#include <string>

#include "base/logging.hh"
#include "base/stats/group.hh"
#include "base/trace.hh"
#include "debug/TutorialLesson07.hh"
#include "sim/cur_tick.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson07
{

TutorialStatsDebugDemo::FlowStats::FlowStats(statistics::Group *parent)
    : statistics::Group(parent, "flow"),
      ADD_STAT(
          attempts,
          statistics::units::Count::get(),
          "Number of issue attempts"),
      ADD_STAT(
          accepted,
          statistics::units::Count::get(),
          "Number of accepted attempts"),
      ADD_STAT(
          dropped,
          statistics::units::Count::get(),
          "Number of dropped attempts"),
      ADD_STAT(
          acceptanceRatio,
          statistics::units::Ratio::get(),
          "Ratio of accepted attempts to total attempts",
          accepted / attempts)
{
}

TutorialStatsDebugDemo::TimingStats::TimingStats(statistics::Group *parent)
    : statistics::Group(parent, "timing"),
      ADD_STAT(
          completions,
          statistics::units::Count::get(),
          "Number of completed tokens"),
      ADD_STAT(
          latencySamples,
          statistics::units::Count::get(),
          "Number of latency samples recorded"),
      ADD_STAT(
          latencyCycleTotal,
          statistics::units::Cycle::get(),
          "Total completion latency in cycles"),
      ADD_STAT(
          clockUpdates,
          statistics::units::Count::get(),
          "Number of clockPeriodUpdated callbacks"),
      ADD_STAT(
          latencyClassCounts,
          statistics::units::Count::get(),
          "Completion counts by latency class"),
      ADD_STAT(
          latencyCycles,
          statistics::units::Cycle::get(),
          "Distribution of completion latencies in cycles"),
      ADD_STAT(
          averageLatencyCycles,
          statistics::units::Cycle::get(),
          "Average completion latency in cycles",
          latencyCycleTotal / latencySamples)
{
    latencyClassCounts.init(2);
    latencyClassCounts.subname(0, "base");
    latencyClassCounts.subname(1, "extended");

    latencyCycles.init(1, 64, 1);
}

TutorialStatsDebugDemo::TutorialStatsDebugDemo(const Params &p)
    : ClockedObject(p),
      issueCount(p.issue_count),
      issueStartCycles(Cycles(p.issue_start_cycles)),
      issueStrideCycles(Cycles(p.issue_stride_cycles)),
      baseLatencyCycles(Cycles(p.base_latency_cycles)),
      latencySpreadCycles(p.latency_spread_cycles),
      dropEvery(p.drop_every),
      flowStats(this),
      timingStats(this),
      issueEvent([this]() { onIssue(); }, name() + ".issue_event")
{
    fatal_if(p.issue_stride_cycles == 0,
             "%s issue_stride_cycles must be >= 1", name());
    fatal_if(p.base_latency_cycles == 0,
             "%s base_latency_cycles must be >= 1", name());

    std::ostringstream details;
    details << "construct issue_count=" << issueCount
            << " issue_start_cycles=" << issueStartCycles
            << " issue_stride_cycles=" << issueStrideCycles
            << " base_latency_cycles=" << baseLatencyCycles
            << " latency_spread_cycles=" << latencySpreadCycles
            << " drop_every=" << dropEvery;
    appendTrace(details.str());
}

void
TutorialStatsDebugDemo::init()
{
    appendTrace("init");
}

void
TutorialStatsDebugDemo::startup()
{
    appendTrace("startup");

    inform("%s startup: issue_count=%u drop_every=%u", name(), issueCount,
           dropEvery);

    if (issueCount == 0) {
        return;
    }

    const Tick first_issue =
        clockEdge() + cyclesToTicks(issueStartCycles);
    schedule(issueEvent, first_issue);
}

void
TutorialStatsDebugDemo::runToCompletion()
{
    while (!eventQueue()->empty()) {
        eventQueue()->serviceOne();
    }
}

void
TutorialStatsDebugDemo::emitDebugProbe(const std::string &tag)
{
    DPRINTF(TutorialLesson07, "probe tag=%s\n", tag.c_str());
    DPRINTFS(
        TutorialLesson07, this, "probe-by-object tag=%s\n",
        tag.c_str());
}

void
TutorialStatsDebugDemo::resetObservabilityStats()
{
    resetStats();
    appendTrace("reset-observability-stats");
}

void
TutorialStatsDebugDemo::appendTrace(const std::string &event)
{
    std::ostringstream line;
    line << "tick=" << curTick()
         << " name=" << name()
         << " event=" << event;
    traceLog.push_back(line.str());
}

void
TutorialStatsDebugDemo::onIssue()
{
    if (nextTokenId > issueCount) {
        return;
    }

    const std::uint64_t token = nextTokenId++;

    flowStats.attempts++;
    DPRINTF(TutorialLesson07, "issue token=%llu\n", token);

    if (dropEvery > 0 && token % dropEvery == 0) {
        flowStats.dropped++;

        std::ostringstream drop;
        drop << "drop token=" << token << " reason=policy";
        appendTrace(drop.str());

        warn("%s drop token=%llu reason=policy", name(), token);
        DPRINTFS(
            TutorialLesson07, this,
            "drop token=%llu reason=policy\n", token);
    } else {
        flowStats.accepted++;

        const unsigned spread_width = latencySpreadCycles + 1;
        const unsigned extra_cycles = latencySpreadCycles == 0 ?
            0 : ((token - 1) % spread_width);
        const Cycles latency = baseLatencyCycles + Cycles(extra_cycles);
        const Tick done_tick = clockEdge() + cyclesToTicks(latency);

        timingStats.latencyClassCounts[
            latency > baseLatencyCycles ? 1 : 0]++;

        std::ostringstream accept;
        accept << "accept token=" << token
               << " latency_cycles=" << latency
               << " done_tick=" << done_tick;
        appendTrace(accept.str());

        DPRINTF(TutorialLesson07,
                "accept token=%llu latency_cycles=%llu done_tick=%llu\n",
                token, static_cast<std::uint64_t>(latency), done_tick);

        const std::string event_name =
            name() + ".completion_event_" + std::to_string(token);
        auto completion_event = std::make_unique<EventFunctionWrapper>(
            [this, token, latency]() { onCompletion(token, latency); },
            event_name);

        schedule(*completion_event, done_tick);
        completionEvents.push_back(std::move(completion_event));
    }

    if (token < issueCount) {
        const Tick next_issue =
            clockEdge() + cyclesToTicks(issueStrideCycles);
        schedule(issueEvent, next_issue);
    }
}

void
TutorialStatsDebugDemo::onCompletion(
    std::uint64_t token,
    Cycles latency_cycles)
{
    timingStats.completions++;
    timingStats.latencySamples++;
    timingStats.latencyCycleTotal +=
        static_cast<std::uint64_t>(latency_cycles);
    timingStats.latencyCycles.sample(
        static_cast<std::uint64_t>(latency_cycles));

    std::ostringstream complete;
    complete << "complete token=" << token
             << " latency_cycles=" << latency_cycles;
    appendTrace(complete.str());

    DPRINTF(
        TutorialLesson07,
        "complete token=%llu latency_cycles=%llu\n",
        token, static_cast<std::uint64_t>(latency_cycles));
    DPRINTFS(TutorialLesson07, this, "completion token=%llu\n", token);
}

void
TutorialStatsDebugDemo::clockPeriodUpdated()
{
    timingStats.clockUpdates++;

    std::ostringstream line;
    line << "clock-period-updated count=" << clockUpdates()
         << " period=" << clockPeriod();
    appendTrace(line.str());

    DPRINTF(
        TutorialLesson07,
        "clock-period-updated count=%llu period=%llu\n",
        clockUpdates(), clockPeriod());
}

std::uint64_t
TutorialStatsDebugDemo::attempts() const
{
    return static_cast<std::uint64_t>(flowStats.attempts.value());
}

std::uint64_t
TutorialStatsDebugDemo::accepted() const
{
    return static_cast<std::uint64_t>(flowStats.accepted.value());
}

std::uint64_t
TutorialStatsDebugDemo::dropped() const
{
    return static_cast<std::uint64_t>(flowStats.dropped.value());
}

double
TutorialStatsDebugDemo::acceptanceRatio() const
{
    return flowStats.acceptanceRatio.total();
}

std::uint64_t
TutorialStatsDebugDemo::completions() const
{
    return static_cast<std::uint64_t>(timingStats.completions.value());
}

std::uint64_t
TutorialStatsDebugDemo::latencySamples() const
{
    return static_cast<std::uint64_t>(timingStats.latencySamples.value());
}

std::uint64_t
TutorialStatsDebugDemo::latencyCycleTotal() const
{
    return static_cast<std::uint64_t>(timingStats.latencyCycleTotal.value());
}

double
TutorialStatsDebugDemo::averageLatencyCycles() const
{
    return timingStats.averageLatencyCycles.total();
}

std::uint64_t
TutorialStatsDebugDemo::shortCompletions() const
{
    statistics::VCounter values;
    timingStats.latencyClassCounts.value(values);
    return static_cast<std::uint64_t>(
        values[0]);
}

std::uint64_t
TutorialStatsDebugDemo::longCompletions() const
{
    statistics::VCounter values;
    timingStats.latencyClassCounts.value(values);
    return static_cast<std::uint64_t>(
        values[1]);
}

std::uint64_t
TutorialStatsDebugDemo::clockUpdates() const
{
    return static_cast<std::uint64_t>(timingStats.clockUpdates.value());
}

bool
TutorialStatsDebugDemo::latencyDistributionEmpty() const
{
    return timingStats.latencyCycles.zero();
}

} // namespace lesson07

} // namespace tutorial

} // namespace gem5
