/* AI-generated by Codex/Claude. */

#ifndef __TUTORIAL_LESSON07_STATS_DEBUG_LOGGING_HH__
#define __TUTORIAL_LESSON07_STATS_DEBUG_LOGGING_HH__

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "base/statistics.hh"
#include "params/TutorialStatsDebugDemo.hh"
#include "sim/clocked_object.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson07
{

/**
 * A ClockedObject used by Lesson 7 to demonstrate stats, debug flags, and
 * logging patterns in one runnable model.
 */
class TutorialStatsDebugDemo : public ClockedObject
{
  public:
    PARAMS(TutorialStatsDebugDemo);
    explicit TutorialStatsDebugDemo(const Params &p);

    void init() override;
    void startup() override;

    void runToCompletion();
    void emitDebugProbe(const std::string &tag);
    void resetObservabilityStats();

    std::uint64_t attempts() const;
    std::uint64_t accepted() const;
    std::uint64_t dropped() const;
    double acceptanceRatio() const;

    std::uint64_t completions() const;
    std::uint64_t latencySamples() const;
    std::uint64_t latencyCycleTotal() const;
    double averageLatencyCycles() const;
    std::uint64_t shortCompletions() const;
    std::uint64_t longCompletions() const;
    std::uint64_t clockUpdates() const;
    bool latencyDistributionEmpty() const;

    const std::vector<std::string> &trace() const
    {
        return traceLog;
    }

  private:
    struct FlowStats : public statistics::Group
    {
        statistics::Scalar attempts;
        statistics::Scalar accepted;
        statistics::Scalar dropped;
        statistics::Formula acceptanceRatio;

        explicit FlowStats(statistics::Group *parent);
    };

    struct TimingStats : public statistics::Group
    {
        statistics::Scalar completions;
        statistics::Scalar latencySamples;
        statistics::Scalar latencyCycleTotal;
        statistics::Scalar clockUpdates;
        statistics::Vector latencyClassCounts;
        statistics::Distribution latencyCycles;
        statistics::Formula averageLatencyCycles;

        explicit TimingStats(statistics::Group *parent);
    };

    void appendTrace(const std::string &event);
    void onIssue();
    void onCompletion(std::uint64_t token, Cycles latency_cycles);
    void clockPeriodUpdated() override;

    const unsigned issueCount;
    const Cycles issueStartCycles;
    const Cycles issueStrideCycles;
    const Cycles baseLatencyCycles;
    const unsigned latencySpreadCycles;
    const unsigned dropEvery;

    std::uint64_t nextTokenId = 1;

    FlowStats flowStats;
    TimingStats timingStats;

    std::vector<std::string> traceLog;
    std::vector<std::unique_ptr<EventFunctionWrapper>> completionEvents;

    EventFunctionWrapper issueEvent;
};

} // namespace lesson07

} // namespace tutorial

} // namespace gem5

#endif // __TUTORIAL_LESSON07_STATS_DEBUG_LOGGING_HH__
