# AI-generated by Codex/Claude.

from m5.objects.ClockedObject import ClockedObject
from m5.params import Param


class TutorialStatsDebugDemo(ClockedObject):
    type = "TutorialStatsDebugDemo"
    cxx_header = "tutorial/lesson07/stats_debug_logging.hh"
    cxx_class = "gem5::tutorial::lesson07::TutorialStatsDebugDemo"

    issue_count = Param.Unsigned(
        6,
        "Number of issue attempts generated from startup()",
    )
    issue_start_cycles = Param.Unsigned(
        1,
        "Cycles from startup() to the first issue",
    )
    issue_stride_cycles = Param.Unsigned(
        1,
        "Cycles between consecutive issue attempts",
    )
    base_latency_cycles = Param.Unsigned(
        1,
        "Base completion latency in cycles for accepted tokens",
    )
    latency_spread_cycles = Param.Unsigned(
        2,
        "Additional latency-cycle spread used to vary completion times",
    )
    drop_every = Param.Unsigned(
        0,
        "Policy drop period: every Nth token is dropped, 0 disables drops",
    )
