/* AI-generated by Codex/Claude. */

#include <gtest/gtest.h>

#include <algorithm>
#include <string>
#include <vector>

#include "params/DerivedClockDomain.hh"
#include "params/SrcClockDomain.hh"
#include "params/TutorialHierarchyDemo.hh"
#include "params/VoltageDomain.hh"
#include "sim/clock_domain.hh"
#include "sim/eventq.hh"
#include "sim/voltage_domain.hh"
#include "tutorial/lesson06/hierarchical_modeling.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson06
{

namespace
{

bool
containsLine(const std::vector<std::string> &lines,
             const std::string &expected)
{
    return std::find(lines.begin(), lines.end(), expected) != lines.end();
}

bool
containsSubstring(const std::vector<std::string> &lines,
                  const std::string &expected)
{
    for (const auto &line : lines) {
        if (line.find(expected) != std::string::npos) {
            return true;
        }
    }

    return false;
}

} // anonymous namespace

class TutorialHierarchyDemoTest : public ::testing::Test
{
  protected:
    EventQueue *queue = nullptr;
    EventQueue *savedQueue = nullptr;

    void
    SetUp() override
    {
        queue = getEventQueue(0);
        savedQueue = curEventQueue();
        curEventQueue(queue);

        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
    }

    void
    TearDown() override
    {
        while (!queue->empty()) {
            queue->serviceOne();
        }
        queue->setCurTick(0);
        curEventQueue(savedQueue);
    }
};

struct DomainBundle
{
    static VoltageDomainParams
    makeVoltageParams()
    {
        VoltageDomainParams params;
        params.name = "tutorial.lesson06.vdd";
        params.eventq_index = 0;
        params.voltage = {1.0, 0.9};
        return params;
    }

    static SrcClockDomainParams
    makeSourceParams(VoltageDomain *voltage_domain)
    {
        SrcClockDomainParams params;
        params.name = "tutorial.lesson06.src_clk";
        params.eventq_index = 0;
        params.clock = {500, 1000};
        params.domain_id = 6;
        params.init_perf_level = 0;
        params.voltage_domain = voltage_domain;
        return params;
    }

    static DerivedClockDomainParams
    makeDerivedParams(ClockDomain *parent_domain)
    {
        DerivedClockDomainParams params;
        params.name = "tutorial.lesson06.mem_clk";
        params.eventq_index = 0;
        params.clk_divider = 2;
        params.clk_domain = parent_domain;
        return params;
    }

    VoltageDomainParams voltageParams;
    VoltageDomain voltageDomain;
    SrcClockDomainParams sourceParams;
    SrcClockDomain sourceDomain;
    DerivedClockDomainParams derivedParams;
    DerivedClockDomain derivedDomain;

    DomainBundle()
        : voltageParams(makeVoltageParams()),
          voltageDomain(voltageParams),
          sourceParams(makeSourceParams(&voltageDomain)),
          sourceDomain(sourceParams),
          derivedParams(makeDerivedParams(&sourceDomain)),
          derivedDomain(derivedParams)
    {
    }
};

TutorialHierarchyDemoParams
makeDemoParams(const std::string &name,
               ClockDomain *parent_domain,
               ClockDomain *frontend_domain,
               ClockDomain *backend_domain,
               unsigned issue_count,
               unsigned issue_start_cycles,
               unsigned issue_stride_cycles,
               unsigned frontend_latency_cycles,
               unsigned backend_latency_cycles)
{
    TutorialHierarchyDemoParams params;
    params.name = name;
    params.eventq_index = 0;
    params.clk_domain = parent_domain;
    params.power_state = nullptr;

    params.issue_count = issue_count;
    params.issue_start_cycles = issue_start_cycles;
    params.issue_stride_cycles = issue_stride_cycles;

    params.frontend_clk_domain = frontend_domain;
    params.backend_clk_domain = backend_domain;
    params.frontend_latency_cycles = frontend_latency_cycles;
    params.backend_latency_cycles = backend_latency_cycles;
    return params;
}

TEST_F(TutorialHierarchyDemoTest, ParentCoordinatesChildrenWithBackpressure)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson06.demo",
        &domains.sourceDomain,
        &domains.sourceDomain,
        &domains.sourceDomain,
        2,
        1,
        1,
        1,
        2);

    TutorialHierarchyDemo demo(params);

    demo.init();
    demo.startup();
    demo.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 3000);

    EXPECT_EQ(demo.issued(), 2u);
    EXPECT_EQ(demo.completed(), 2u);
    EXPECT_EQ(demo.frontend().processed(), 2u);
    EXPECT_EQ(demo.backend().processed(), 2u);

    EXPECT_EQ(demo.frontendQueueDepth(), 0u);
    EXPECT_EQ(demo.backendQueueDepth(), 0u);

    EXPECT_TRUE(containsLine(
        demo.trace(),
        "tick=1500 name=tutorial.lesson06.demo "
        "backend-queue token=2 depth=1"));
    EXPECT_TRUE(containsLine(
        demo.trace(),
        "tick=3000 name=tutorial.lesson06.demo all-complete"));

    EXPECT_EQ(demo.backend().trace().back(),
              "tick=3000 stage=tutorial.lesson06.demo.backend "
              "event=complete token=2 period=500 cycle=6 edge=3000 "
              "next=3500");
}

TEST_F(TutorialHierarchyDemoTest, ChildClockDomainsChangeCompletionTicks)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson06.domains",
        &domains.sourceDomain,
        &domains.sourceDomain,
        &domains.derivedDomain,
        1,
        1,
        1,
        1,
        1);

    TutorialHierarchyDemo demo(params);

    demo.init();
    demo.startup();
    demo.runToCompletion();

    EXPECT_TRUE(queue->empty());
    EXPECT_EQ(queue->getCurTick(), 2000);

    EXPECT_EQ(demo.issued(), 1u);
    EXPECT_EQ(demo.completed(), 1u);

    EXPECT_TRUE(containsLine(
        demo.frontend().trace(),
        "tick=1000 stage=tutorial.lesson06.domains.frontend "
        "event=complete token=1 period=500 cycle=2 edge=1000 "
        "next=1500"));
    EXPECT_TRUE(containsLine(
        demo.backend().trace(),
        "tick=2000 stage=tutorial.lesson06.domains.backend "
        "event=complete token=1 period=1000 cycle=2 edge=2000 "
        "next=3000"));
}

TEST_F(TutorialHierarchyDemoTest, DvfsPropagatesToParentAndChildren)
{
    DomainBundle domains;
    auto params = makeDemoParams(
        "tutorial.lesson06.dvfs",
        &domains.sourceDomain,
        &domains.sourceDomain,
        &domains.derivedDomain,
        0,
        1,
        1,
        1,
        1);

    TutorialHierarchyDemo demo(params);

    demo.init();
    demo.startup();

    queue->setCurTick(750);
    domains.sourceDomain.perfLevel(1);

    EXPECT_EQ(domains.sourceDomain.clockPeriod(), 1000);
    EXPECT_EQ(domains.derivedDomain.clockPeriod(), 2000);

    EXPECT_EQ(demo.clockUpdates(), 1u);
    EXPECT_EQ(demo.frontend().clockUpdates(), 1u);
    EXPECT_EQ(demo.backend().clockUpdates(), 1u);

    EXPECT_TRUE(containsSubstring(
        demo.trace(),
        "name=tutorial.lesson06.dvfs clock-period-updated count=1"));
    EXPECT_TRUE(containsSubstring(
        demo.frontend().trace(),
        "stage=tutorial.lesson06.dvfs.frontend "
        "event=clock-period-updated count=1"));
    EXPECT_TRUE(containsSubstring(
        demo.backend().trace(),
        "stage=tutorial.lesson06.dvfs.backend "
        "event=clock-period-updated count=1"));
}

} // namespace lesson06

} // namespace tutorial

} // namespace gem5
