/* AI-generated by Codex/Claude. */

#ifndef __TUTORIAL_LESSON06_HIERARCHICAL_MODELING_HH__
#define __TUTORIAL_LESSON06_HIERARCHICAL_MODELING_HH__

#include <cstdint>
#include <deque>
#include <functional>
#include <string>
#include <vector>

#include "params/TutorialHierarchyDemo.hh"
#include "params/TutorialHierarchyStage.hh"
#include "sim/clocked_object.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson06
{

/**
 * Child ClockedObject used by Lesson 6 to model one pipeline stage.
 *
 * Each stage accepts one token at a time, schedules completion after a
 * configurable cycle delay, and invokes a callback back into the parent.
 */
class TutorialHierarchyStage : public ClockedObject
{
  public:
    PARAMS(TutorialHierarchyStage);
    explicit TutorialHierarchyStage(const Params &p);

    void init() override;
    void startup() override;

    bool tryAccept(std::uint64_t token, const std::string &boundary);

    bool busy() const { return completionEvent.scheduled(); }
    Cycles latency() const { return latencyCycles; }

    std::uint64_t processed() const { return processedCount; }
    std::uint64_t clockUpdates() const { return clockUpdateCount; }

    const std::vector<std::string> &trace() const
    {
        return stageLog;
    }

    void setCompletionCallback(std::function<void(std::uint64_t)> callback)
    {
        completionCallback = std::move(callback);
    }

  private:
    void append(const std::string &event);
    void onCompletion();
    void clockPeriodUpdated() override;

    const Cycles latencyCycles;

    std::function<void(std::uint64_t)> completionCallback;

    std::uint64_t inflightToken = 0;
    std::uint64_t processedCount = 0;
    std::uint64_t clockUpdateCount = 0;

    std::vector<std::string> stageLog;

    EventFunctionWrapper completionEvent;
};

/**
 * Parent ClockedObject used by Lesson 6 to coordinate two child stages.
 *
 * The parent owns child objects, issues tokens according to parent-level
 * policy, and handles backpressure by queueing tokens between boundaries.
 */
class TutorialHierarchyDemo : public ClockedObject
{
  public:
    PARAMS(TutorialHierarchyDemo);
    explicit TutorialHierarchyDemo(const Params &p);

    void init() override;
    void startup() override;

    void runToCompletion();

    std::uint64_t issued() const { return issuedCount; }
    std::uint64_t completed() const { return completedCount; }
    std::uint64_t clockUpdates() const { return clockUpdateCount; }

    std::size_t frontendQueueDepth() const { return pendingFrontend.size(); }
    std::size_t backendQueueDepth() const { return pendingBackend.size(); }

    const TutorialHierarchyStage &frontend() const { return frontendStage; }
    const TutorialHierarchyStage &backend() const { return backendStage; }

    const std::vector<std::string> &trace() const
    {
        return parentLog;
    }

  private:
    static TutorialHierarchyStageParams makeStageParams(
        const Params &parent_params,
        const std::string &suffix,
        ClockDomain *clock_domain,
        unsigned latency_cycles);

    void append(const std::string &event);
    void onIssue();
    void onFrontendDone(std::uint64_t token);
    void onBackendDone(std::uint64_t token);

    void dispatchFrontend();
    void dispatchBackend();
    void clockPeriodUpdated() override;

    const Cycles issueStartCycles;
    const Cycles issueStrideCycles;
    const unsigned issueLimit;

    TutorialHierarchyStageParams frontendParams;
    TutorialHierarchyStageParams backendParams;

    TutorialHierarchyStage frontendStage;
    TutorialHierarchyStage backendStage;

    std::uint64_t nextTokenId = 1;
    std::uint64_t issuedCount = 0;
    std::uint64_t completedCount = 0;
    std::uint64_t clockUpdateCount = 0;

    std::deque<std::uint64_t> pendingFrontend;
    std::deque<std::uint64_t> pendingBackend;

    std::vector<std::string> parentLog;

    EventFunctionWrapper issueEvent;
};

} // namespace lesson06

} // namespace tutorial

} // namespace gem5

#endif // __TUTORIAL_LESSON06_HIERARCHICAL_MODELING_HH__
