/* AI-generated by Codex/Claude. */

#include "tutorial/lesson06/hierarchical_modeling.hh"

#include <sstream>

#include "base/logging.hh"
#include "sim/cur_tick.hh"

namespace gem5
{

namespace tutorial
{

namespace lesson06
{

TutorialHierarchyStage::TutorialHierarchyStage(const Params &p)
    : ClockedObject(p),
      latencyCycles(Cycles(p.latency_cycles)),
      completionEvent(
          [this]() { onCompletion(); },
          name() + ".completion_event")
{
    fatal_if(p.latency_cycles == 0,
             "%s latency_cycles must be >= 1", name());

    std::ostringstream details;
    details << "construct latency_cycles=" << latencyCycles;
    append(details.str());
}

void
TutorialHierarchyStage::init()
{
    append("init");
}

void
TutorialHierarchyStage::startup()
{
    append("startup");
}

bool
TutorialHierarchyStage::tryAccept(
    std::uint64_t token,
    const std::string &boundary)
{
    if (completionEvent.scheduled()) {
        std::ostringstream reject;
        reject << "reject token=" << token
               << " boundary=" << boundary
               << " reason=busy";
        append(reject.str());
        return false;
    }

    inflightToken = token;

    const Tick done_tick = clockEdge() + cyclesToTicks(latencyCycles);

    std::ostringstream accept;
    accept << "accept token=" << token
           << " boundary=" << boundary
           << " done_tick=" << done_tick;
    append(accept.str());

    schedule(completionEvent, done_tick);
    return true;
}

void
TutorialHierarchyStage::append(const std::string &event)
{
    std::ostringstream line;
    line << "tick=" << curTick()
         << " stage=" << name()
         << " event=" << event
         << " period=" << clockPeriod()
         << " cycle=" << curCycle()
         << " edge=" << clockEdge()
         << " next=" << nextCycle();
    stageLog.push_back(line.str());
}

void
TutorialHierarchyStage::onCompletion()
{
    processedCount++;

    std::ostringstream done;
    done << "complete token=" << inflightToken;
    append(done.str());

    const std::uint64_t token = inflightToken;
    inflightToken = 0;

    if (completionCallback) {
        completionCallback(token);
    }
}

void
TutorialHierarchyStage::clockPeriodUpdated()
{
    clockUpdateCount++;

    std::ostringstream update;
    update << "clock-period-updated count=" << clockUpdateCount;
    append(update.str());
}

TutorialHierarchyStageParams
TutorialHierarchyDemo::makeStageParams(
    const Params &parent_params,
    const std::string &suffix,
    ClockDomain *clock_domain,
    unsigned latency_cycles)
{
    TutorialHierarchyStageParams params;
    params.name = parent_params.name + "." + suffix;
    params.eventq_index = parent_params.eventq_index;
    params.clk_domain = clock_domain;
    params.power_state = nullptr;
    params.latency_cycles = latency_cycles;
    return params;
}

TutorialHierarchyDemo::TutorialHierarchyDemo(const Params &p)
    : ClockedObject(p),
      issueStartCycles(Cycles(p.issue_start_cycles)),
      issueStrideCycles(Cycles(p.issue_stride_cycles)),
      issueLimit(p.issue_count),
      frontendParams(
          makeStageParams(
              p,
              "frontend",
              p.frontend_clk_domain,
              p.frontend_latency_cycles)),
      backendParams(
          makeStageParams(
              p,
              "backend",
              p.backend_clk_domain,
              p.backend_latency_cycles)),
      frontendStage(frontendParams),
      backendStage(backendParams),
      issueEvent([this]() { onIssue(); }, name() + ".issue_event")
{
    fatal_if(p.issue_stride_cycles == 0,
             "%s issue_stride_cycles must be >= 1", name());
    fatal_if(p.frontend_latency_cycles == 0,
             "%s frontend_latency_cycles must be >= 1", name());
    fatal_if(p.backend_latency_cycles == 0,
             "%s backend_latency_cycles must be >= 1", name());

    frontendStage.setCompletionCallback(
        [this](std::uint64_t token) { onFrontendDone(token); });
    backendStage.setCompletionCallback(
        [this](std::uint64_t token) { onBackendDone(token); });

    std::ostringstream details;
    details << "construct issue_count=" << issueLimit
            << " issue_start_cycles=" << issueStartCycles
            << " issue_stride_cycles=" << issueStrideCycles
            << " frontend_latency_cycles="
            << frontendStage.latency()
            << " backend_latency_cycles="
            << backendStage.latency();
    append(details.str());
}

void
TutorialHierarchyDemo::init()
{
    append("init");
    frontendStage.init();
    backendStage.init();
}

void
TutorialHierarchyDemo::startup()
{
    append("startup");
    frontendStage.startup();
    backendStage.startup();

    if (issueLimit == 0) {
        return;
    }

    const Tick first_issue =
        clockEdge() + cyclesToTicks(issueStartCycles);
    schedule(issueEvent, first_issue);
}

void
TutorialHierarchyDemo::runToCompletion()
{
    while (!eventQueue()->empty()) {
        eventQueue()->serviceOne();
    }
}

void
TutorialHierarchyDemo::append(const std::string &event)
{
    std::ostringstream line;
    line << "tick=" << curTick()
         << " name=" << name()
         << " " << event;
    parentLog.push_back(line.str());
}

void
TutorialHierarchyDemo::onIssue()
{
    if (issuedCount >= issueLimit) {
        return;
    }

    const std::uint64_t token = nextTokenId++;
    issuedCount++;

    std::ostringstream line;
    line << "issue token=" << token;
    append(line.str());

    if (!frontendStage.tryAccept(token, "parent->frontend")) {
        pendingFrontend.push_back(token);

        std::ostringstream queued;
        queued << "frontend-queue token=" << token
               << " depth=" << pendingFrontend.size();
        append(queued.str());
    }

    if (issuedCount < issueLimit) {
        const Tick next_issue =
            clockEdge() + cyclesToTicks(issueStrideCycles);
        schedule(issueEvent, next_issue);
    }
}

void
TutorialHierarchyDemo::onFrontendDone(std::uint64_t token)
{
    std::ostringstream done;
    done << "frontend-done token=" << token;
    append(done.str());

    pendingBackend.push_back(token);

    if (backendStage.busy()) {
        std::ostringstream queued;
        queued << "backend-queue token=" << token
               << " depth=" << pendingBackend.size();
        append(queued.str());
    }

    dispatchFrontend();
    dispatchBackend();
}

void
TutorialHierarchyDemo::onBackendDone(std::uint64_t token)
{
    completedCount++;

    std::ostringstream done;
    done << "backend-done token=" << token
         << " completed=" << completedCount;
    append(done.str());

    dispatchBackend();

    if (completedCount == issueLimit) {
        append("all-complete");
    }
}

void
TutorialHierarchyDemo::dispatchFrontend()
{
    if (frontendStage.busy() || pendingFrontend.empty()) {
        return;
    }

    const std::uint64_t token = pendingFrontend.front();
    pendingFrontend.pop_front();

    std::ostringstream dispatch;
    dispatch << "dispatch-frontend token=" << token;
    append(dispatch.str());

    const bool accepted =
        frontendStage.tryAccept(token, "queue->frontend");
    panic_if(!accepted,
             "%s dispatchFrontend expected idle frontend", name());
}

void
TutorialHierarchyDemo::dispatchBackend()
{
    if (backendStage.busy() || pendingBackend.empty()) {
        return;
    }

    const std::uint64_t token = pendingBackend.front();
    pendingBackend.pop_front();

    std::ostringstream dispatch;
    dispatch << "dispatch-backend token=" << token;
    append(dispatch.str());

    const bool accepted =
        backendStage.tryAccept(token, "queue->backend");
    panic_if(!accepted,
             "%s dispatchBackend expected idle backend", name());
}

void
TutorialHierarchyDemo::clockPeriodUpdated()
{
    clockUpdateCount++;

    std::ostringstream update;
    update << "clock-period-updated count=" << clockUpdateCount
           << " period=" << clockPeriod();
    append(update.str());
}

} // namespace lesson06

} // namespace tutorial

} // namespace gem5
