# AI-generated by Codex/Claude.

from m5.objects.ClockedObject import ClockedObject
from m5.params import Param
from m5.proxy import Parent


class TutorialHierarchyStage(ClockedObject):
    type = "TutorialHierarchyStage"
    cxx_header = "tutorial/lesson06/hierarchical_modeling.hh"
    cxx_class = "gem5::tutorial::lesson06::TutorialHierarchyStage"

    latency_cycles = Param.Unsigned(
        1,
        "Cycles between stage accept and stage completion",
    )


class TutorialHierarchyDemo(ClockedObject):
    type = "TutorialHierarchyDemo"
    cxx_header = "tutorial/lesson06/hierarchical_modeling.hh"
    cxx_class = "gem5::tutorial::lesson06::TutorialHierarchyDemo"

    issue_count = Param.Unsigned(
        3,
        "Number of tokens issued by the parent aggregator",
    )
    issue_start_cycles = Param.Unsigned(
        1,
        "Cycles from startup() to first issue",
    )
    issue_stride_cycles = Param.Unsigned(
        1,
        "Cycles between parent issue attempts",
    )

    frontend_clk_domain = Param.ClockDomain(
        Parent.clk_domain,
        "Clock domain used by the frontend child stage",
    )
    backend_clk_domain = Param.ClockDomain(
        Parent.clk_domain,
        "Clock domain used by the backend child stage",
    )

    frontend_latency_cycles = Param.Unsigned(
        1,
        "Frontend stage service latency in cycles",
    )
    backend_latency_cycles = Param.Unsigned(
        2,
        "Backend stage service latency in cycles",
    )
